/* 
  This file was generated automatically with ./scripts/maple2c.pl.
  Do not edit this file directly as it can be overwritten!!

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Maple version     : Maple 2016 (X86 64 LINUX)
  Maple source      : ./maple/mgga_exc/mgga_x_ms.mpl
  Type of functional: mgga_exc
*/

#define maple2c_order 2
#define MAPLE2C_FLAGS (XC_FLAGS_I_HAVE_EXC | XC_FLAGS_I_HAVE_VXC | XC_FLAGS_I_HAVE_FXC)


static inline void
func_unpol(const xc_func_type *p, int order, const double *rho, const double *sigma, const double *lapl, const double *tau , double *zk MGGA_OUT_PARAMS_NO_EXC(XC_COMMA double *, ))
{

#ifndef XC_DONT_COMPILE_EXC
  double t4, t5, t6, t8, t9, t10, t11, t12;
  double t13, t14, t16, t17, t18, t19, t20, t22;
  double t23, t25, t26, t30, t31, t33, t36, t37;
  double t38, t41, t44, t45, t46, t48, t49, t52;
  double t55, t56, t59, t60, t61, t62, t67, t69;
  double t73;

#ifndef XC_DONT_COMPILE_VXC
  double t74, t78, t79, t82, t83, t84, t86, t87;
  double t88, t89, t91, t92, t93, t98, t100, t103;
  double t104, t105, t106, t110, t114, t117, t120, t123;
  double t125, t130, t133, t134, t135, t137, t138, t139;
  double t140, t141, t142, t144, t146, t148, t150, t151;
  double t155, t157, t161, t163, t164, t172, t173, t175;
  double t179;

#ifndef XC_DONT_COMPILE_FXC
  double t191, t192, t194, t199, t201, t203, t205, t207;
  double t208, t212, t213, t218, t219, t235, t242, t243;
  double t250, t255, t268, t275, t280, t286, t291, t293;
  double t294, t296, t298, t299, t300, t309, t313, t331;
  double t351, t356, t362, t375, t397, t402, t403, t404;
  double t406, t415, t421, t430, t445, t448, t449, t484;
  double t487, t488, t499, t515;
#endif

#endif

#endif


  mgga_x_ms_params *params;

  assert(p->params != NULL);
  params = (mgga_x_ms_params * ) (p->params);

  t4 = rho[0] / 0.2e1 <= 0.101e1 * p->threshold_dens;
  t5 = M_CBRT3;
  t6 = M_CBRTPI;
  t8 = t5 / t6;
  t9 = POW_1_3(rho[0]);
  t10 = M_CBRT6;
  t11 = M_PI * M_PI;
  t12 = POW_1_3(t11);
  t13 = t12 * t12;
  t14 = 0.1e1 / t13;
  t16 = M_CBRT2;
  t17 = t16 * t16;
  t18 = sigma[0] * t17;
  t19 = rho[0] * rho[0];
  t20 = t9 * t9;
  t22 = 0.1e1 / t20 / t19;
  t23 = t18 * t22;
  t25 = 0.5e1 / 0.972e3 * t10 * t14 * t23;
  t26 = params->kappa + t25;
  t30 = params->kappa * (0.1e1 - params->kappa / t26);
  t31 = tau[0] * t17;
  t33 = 0.1e1 / t20 / rho[0];
  t36 = t31 * t33 - t23 / 0.8e1;
  t37 = t36 * t36;
  t38 = t10 * t10;
  t41 = 0.1e1 / t12 / t11;
  t44 = 0.1e1 - 0.25e2 / 0.81e2 * t37 * t38 * t41;
  t45 = t44 * t44;
  t46 = t45 * t44;
  t48 = t11 * t11;
  t49 = 0.1e1 / t48;
  t52 = t37 * t37;
  t55 = t48 * t48;
  t56 = 0.1e1 / t55;
  t59 = 0.1e1 + 0.250e3 / 0.243e3 * t37 * t36 * t49 + 0.62500e5 / 0.59049e5 * params->b * t52 * t37 * t56;
  t60 = 0.1e1 / t59;
  t61 = t46 * t60;
  t62 = params->kappa + t25 + params->c;
  t67 = params->kappa * (0.1e1 - params->kappa / t62) - t30;
  t69 = t61 * t67 + t30 + 0.1e1;
  t73 = my_piecewise3(t4, 0, -0.3e1 / 0.8e1 * t8 * t9 * t69);
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    zk[0] = 0.2e1 * t73;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  t74 = 0.1e1 / t20;
  t78 = params->kappa * params->kappa;
  t79 = t26 * t26;
  t82 = t78 / t79 * t10;
  t83 = t14 * sigma[0];
  t84 = t19 * rho[0];
  t86 = 0.1e1 / t20 / t84;
  t87 = t17 * t86;
  t88 = t83 * t87;
  t89 = t82 * t88;
  t91 = t45 * t60;
  t92 = t91 * t67;
  t93 = t36 * t38;
  t98 = -0.5e1 / 0.3e1 * t31 * t22 + t18 * t86 / 0.3e1;
  t100 = t93 * t41 * t98;
  t103 = t59 * t59;
  t104 = 0.1e1 / t103;
  t105 = t46 * t104;
  t106 = t37 * t49;
  t110 = params->b * t52 * t36;
  t114 = 0.250e3 / 0.81e2 * t106 * t98 + 0.125000e6 / 0.19683e5 * t110 * t56 * t98;
  t117 = t62 * t62;
  t120 = t78 / t117 * t10;
  t123 = -0.10e2 / 0.729e3 * t120 * t88 + 0.10e2 / 0.729e3 * t89;
  t125 = -0.10e2 / 0.729e3 * t89 - 0.50e2 / 0.27e2 * t92 * t100 - t105 * t67 * t114 + t61 * t123;
  t130 = my_piecewise3(t4, 0, -t8 * t74 * t69 / 0.8e1 - 0.3e1 / 0.8e1 * t8 * t9 * t125);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = 0.2e1 * rho[0] * t130 + 0.2e1 * t73;

  t133 = t14 * t17;
  t134 = t133 * t22;
  t135 = t82 * t134;
  t137 = t67 * t36;
  t138 = t91 * t137;
  t139 = t38 * t41;
  t140 = t17 * t22;
  t141 = t139 * t140;
  t142 = t138 * t141;
  t144 = t106 * t140;
  t146 = t56 * t17;
  t148 = t110 * t146 * t22;
  t150 = -0.125e3 / 0.324e3 * t144 - 0.15625e5 / 0.19683e5 * t148;
  t151 = t67 * t150;
  t155 = 0.5e1 / 0.972e3 * t120 * t134 - 0.5e1 / 0.972e3 * t135;
  t157 = 0.5e1 / 0.972e3 * t135 + 0.25e2 / 0.108e3 * t142 - t105 * t151 + t61 * t155;
  t161 = my_piecewise3(t4, 0, -0.3e1 / 0.8e1 * t8 * t9 * t157);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[0] = 0.2e1 * rho[0] * t161;

  if(vrho != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vlapl[0] = 0.0e0;

  t163 = t17 * t33;
  t164 = t139 * t163;
  t172 = 0.250e3 / 0.81e2 * t106 * t163 + 0.125000e6 / 0.19683e5 * t110 * t146 * t33;
  t173 = t67 * t172;
  t175 = -0.50e2 / 0.27e2 * t138 * t164 - t105 * t173;
  t179 = my_piecewise3(t4, 0, -0.3e1 / 0.8e1 * t8 * t9 * t175);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vtau[0] = 0.2e1 * rho[0] * t179;

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t191 = t78 / t79 / t26 * t38;
  t192 = sigma[0] * sigma[0];
  t194 = t19 * t19;
  t199 = t41 * t192 * t16 / t9 / t194 / t84;
  t201 = 0.400e3 / 0.531441e6 * t191 * t199;
  t203 = 0.1e1 / t20 / t194;
  t205 = t83 * t17 * t203;
  t207 = 0.110e3 / 0.2187e4 * t82 * t205;
  t208 = t44 * t60;
  t212 = 0.1e1 / t13 / t48;
  t213 = t98 * t98;
  t218 = t45 * t104;
  t219 = t218 * t137;
  t235 = 0.40e2 / 0.9e1 * t31 * t86 - 0.11e2 / 0.9e1 * t18 * t203;
  t242 = t46 / t103 / t59;
  t243 = t114 * t114;
  t250 = t36 * t49;
  t255 = params->b * t52;
  t268 = t78 / t117 / t62 * t38;
  t275 = -t201 + t207 + 0.10000e5 / 0.729e3 * t208 * t67 * t37 * t10 * t212 * t213 + 0.100e3 / 0.27e2 * t219 * t139 * t98 * t114 - 0.100e3 / 0.27e2 * t91 * t123 * t100 - 0.50e2 / 0.27e2 * t92 * t213 * t38 * t41 - 0.50e2 / 0.27e2 * t92 * t93 * t41 * t235 + 0.2e1 * t242 * t67 * t243 - 0.2e1 * t105 * t123 * t114 - t105 * t67 * (0.500e3 / 0.81e2 * t250 * t213 + 0.250e3 / 0.81e2 * t106 * t235 + 0.625000e6 / 0.19683e5 * t255 * t56 * t213 + 0.125000e6 / 0.19683e5 * t110 * t56 * t235) + t61 * (-0.400e3 / 0.531441e6 * t268 * t199 + 0.110e3 / 0.2187e4 * t120 * t205 + t201 - t207);
  t280 = my_piecewise3(t4, 0, t8 * t33 * t69 / 0.12e2 - t8 * t74 * t125 / 0.4e1 - 0.3e1 / 0.8e1 * t8 * t9 * t275);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = 0.2e1 * rho[0] * t280 + 0.4e1 * t130;

  t286 = t41 * t16;
  t291 = t286 / t9 / t194 / t19 * sigma[0];
  t293 = 0.50e2 / 0.177147e6 * t191 * t291;
  t294 = t133 * t86;
  t296 = 0.10e2 / 0.729e3 * t82 * t294;
  t298 = t208 * t67 * t37;
  t299 = t10 * t212;
  t300 = t140 * t98;
  t309 = t91 * t123 * t36;
  t313 = t91 * t67 * t98;
  t331 = t255 * t56;
  t351 = t293 - t296 - 0.1250e4 / 0.729e3 * t298 * t299 * t300 - 0.25e2 / 0.108e3 * t219 * t139 * t140 * t114 + 0.25e2 / 0.108e3 * t309 * t141 + 0.25e2 / 0.108e3 * t313 * t141 - 0.50e2 / 0.81e2 * t138 * t139 * t87 + 0.50e2 / 0.27e2 * t218 * t151 * t100 + 0.2e1 * t242 * t151 * t114 - t105 * t123 * t150 - t105 * t67 * (-0.125e3 / 0.162e3 * t250 * t300 + 0.250e3 / 0.243e3 * t106 * t87 - 0.78125e5 / 0.19683e5 * t331 * t300 + 0.125000e6 / 0.59049e5 * t110 * t146 * t86) - 0.50e2 / 0.27e2 * t91 * t155 * t100 - t105 * t155 * t114 + t61 * (0.50e2 / 0.177147e6 * t268 * t291 - 0.10e2 / 0.729e3 * t120 * t294 - t293 + t296);
  t356 = my_piecewise3(t4, 0, -t8 * t74 * t157 / 0.8e1 - 0.3e1 / 0.8e1 * t8 * t9 * t351);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[0] = 0.2e1 * rho[0] * t356 + 0.2e1 * t161;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rholapl[0] = 0.0e0;

  t362 = t163 * t98;
  t375 = t218 * t173;
  t397 = my_piecewise3(t4, 0, -t8 * t74 * t175 / 0.8e1 - 0.3e1 / 0.8e1 * t8 * t9 * (0.10000e5 / 0.729e3 * t298 * t299 * t362 + 0.50e2 / 0.27e2 * t219 * t139 * t163 * t114 - 0.50e2 / 0.27e2 * t309 * t164 - 0.50e2 / 0.27e2 * t313 * t164 + 0.250e3 / 0.81e2 * t142 + 0.50e2 / 0.27e2 * t375 * t100 + 0.2e1 * t242 * t173 * t114 - t105 * t123 * t172 - t105 * t67 * (0.500e3 / 0.81e2 * t250 * t362 - 0.1250e4 / 0.243e3 * t144 + 0.625000e6 / 0.19683e5 * t331 * t362 - 0.625000e6 / 0.59049e5 * t148)));
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhotau[0] = 0.2e1 * rho[0] * t397 + 0.2e1 * t179;

  t402 = 0.1e1 / t9 / t194 / rho[0];
  t403 = t286 * t402;
  t404 = t191 * t403;
  t406 = t16 * t402;
  t415 = t91 * t155 * t36;
  t421 = t150 * t150;
  t430 = t56 * t16;
  t445 = my_piecewise3(t4, 0, -0.3e1 / 0.8e1 * t8 * t9 * (-0.25e2 / 0.236196e6 * t404 + 0.625e3 / 0.1458e4 * t298 * t299 * t406 - 0.25e2 / 0.54e2 * t219 * t139 * t140 * t150 + 0.25e2 / 0.54e2 * t415 * t141 - 0.25e2 / 0.432e3 * t92 * t406 * t139 + 0.2e1 * t242 * t67 * t421 - 0.2e1 * t105 * t155 * t150 - t105 * t67 * (0.125e3 / 0.648e3 * t250 * t406 + 0.78125e5 / 0.78732e5 * t255 * t430 * t402) + t61 * (-0.25e2 / 0.236196e6 * t268 * t403 + 0.25e2 / 0.236196e6 * t404)));
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[0] = 0.2e1 * rho[0] * t445;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmalapl[0] = 0.0e0;

  t448 = 0.1e1 / t9 / t194;
  t449 = t16 * t448;
  t484 = my_piecewise3(t4, 0, -0.3e1 / 0.8e1 * t8 * t9 * (-0.2500e4 / 0.729e3 * t298 * t299 * t449 + 0.50e2 / 0.27e2 * t219 * t139 * t163 * t150 - 0.50e2 / 0.27e2 * t415 * t164 + 0.25e2 / 0.54e2 * t92 * t449 * t139 - 0.25e2 / 0.108e3 * t375 * t93 * t41 * t17 * t22 + 0.2e1 * t242 * t173 * t150 - t105 * t155 * t172 - t105 * t67 * (-0.125e3 / 0.81e2 * t250 * t449 - 0.156250e6 / 0.19683e5 * t255 * t430 * t448)));
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmatau[0] = 0.2e1 * rho[0] * t484;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2lapl2[0] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2lapltau[0] = 0.0e0;

  t487 = 0.1e1 / t9 / t84;
  t488 = t16 * t487;
  t499 = t172 * t172;
  t515 = my_piecewise3(t4, 0, -0.3e1 / 0.8e1 * t8 * t9 * (0.20000e5 / 0.729e3 * t298 * t299 * t488 + 0.100e3 / 0.27e2 * t219 * t139 * t163 * t172 - 0.100e3 / 0.27e2 * t92 * t488 * t139 + 0.2e1 * t242 * t67 * t499 - t105 * t67 * (0.1000e4 / 0.81e2 * t250 * t488 + 0.1250000e7 / 0.19683e5 * t255 * t430 * t487)));
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2tau2[0] = 0.2e1 * rho[0] * t515;

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


#endif

#endif

#endif


}


static inline void
func_pol(const xc_func_type *p, int order, const double *rho, const double *sigma, const double *lapl, const double *tau , double *zk MGGA_OUT_PARAMS_NO_EXC(XC_COMMA double *, ))
{

#ifndef XC_DONT_COMPILE_EXC
  double t2, t3, t4, t5, t7, t8, t9, t10;
  double t11, t12, t13, t14, t15, t16, t17, t18;
  double t19, t20, t21, t22, t23, t24, t25, t26;
  double t28, t29, t31, t32, t36, t38, t41, t42;
  double t43, t46, t49, t50, t51, t53, t54, t57;
  double t60, t61, t64, t65, t66, t67, t72, t74;
  double t75, t79, t80, t81, t82, t83, t84, t85;
  double t86, t88, t89, t91, t92, t96, t98, t101;
  double t102, t106, t107, t108, t112, t117, t118, t119;
  double t120, t125, t127, t128, t132;

#ifndef XC_DONT_COMPILE_VXC
  double t133, t138, t139, t142, t144, t145, t146, t147;
  double t148, t149, t151, t152, t153, t156, t157, t159;
  double t160, t161, t162, t164, t165, t166, t168, t169;
  double t170, t175, t177, t180, t181, t182, t183, t187;
  double t191, t194, t196, t197, t200, t202, t203, t208;
  double t209, t212, t214, t215, t216, t217, t218, t223;
  double t226, t227, t232, t233, t238, t239, t241, t242;
  double t243, t246, t248, t249, t250, t251, t253, t254;
  double t255, t257, t258, t259, t264, t266, t269, t270;
  double t271, t272, t276, t280, t283, t285, t286, t289;
  double t291, t292, t297, t300, t301, t303, t304, t305;
  double t307, t309, t310, t312, t313, t317, t319, t320;
  double t324, t325, t326, t328, t329, t330, t332, t334;
  double t335, t337, t338, t342, t344, t345, t349, t350;
  double t351, t356, t359, t360, t362, t363, t367, t368;
  double t369, t374, t377, t378, t380, t381, t385;

#ifndef XC_DONT_COMPILE_FXC
  double t390, t396, t399, t402, t405, t407, t409, t418;
  double t419, t429, t430, t431, t433, t437, t439, t441;
  double t442, t444, t445, t446, t447, t449, t450, t455;
  double t457, t458, t463, t474, t481, t482, t489, t494;
  double t506, t507, t514, t520, t524, t526, t529, t531;
  double t533, t536, t542, t553, t566, t569, t579, t587;
  double t595, t602, t614, t622, t639, t640, t641, t643;
  double t647, t649, t651, t652, t654, t655, t656, t657;
  double t658, t663, t665, t670, t681, t688, t689, t696;
  double t701, t713, t714, t721, t727, t735, t744, t746;
  double t747, t749, t751, t752, t753, t763, t792, t803;
  double t809, t813, t819, t826, t839, t841, t842, t844;
  double t846, t847, t857, t886, t897, t903, t910, t915;
  double t929, t953, t957, t963, t970, t979, t993, t1017;
  double t1021, t1022, t1023, t1037, t1061, t1064, t1065, t1066;
  double t1080, t1104, t1106, t1141, t1143, t1178, t1180, t1193;
  double t1210, t1212, t1225, t1242;
#endif

#endif

#endif


  mgga_x_ms_params *params;

  assert(p->params != NULL);
  params = (mgga_x_ms_params * ) (p->params);

  t2 = 0.101e1 * p->threshold_dens;
  t3 = rho[0] <= t2;
  t4 = M_CBRT3;
  t5 = M_CBRTPI;
  t7 = t4 / t5;
  t8 = M_CBRT2;
  t9 = t7 * t8;
  t10 = rho[0] + rho[1];
  t11 = POW_1_3(t10);
  t12 = t11 * t11;
  t13 = 0.1e1 / t12;
  t14 = rho[0] * t13;
  t15 = 0.1e1 / t10;
  t16 = rho[0] * t15;
  t17 = POW_1_3(t16);
  t18 = M_CBRT6;
  t19 = M_PI * M_PI;
  t20 = POW_1_3(t19);
  t21 = t20 * t20;
  t22 = 0.1e1 / t21;
  t23 = t18 * t22;
  t24 = rho[0] * rho[0];
  t25 = POW_1_3(rho[0]);
  t26 = t25 * t25;
  t28 = 0.1e1 / t26 / t24;
  t29 = sigma[0] * t28;
  t31 = 0.5e1 / 0.972e3 * t23 * t29;
  t32 = params->kappa + t31;
  t36 = params->kappa * (0.1e1 - params->kappa / t32);
  t38 = 0.1e1 / t26 / rho[0];
  t41 = tau[0] * t38 - t29 / 0.8e1;
  t42 = t41 * t41;
  t43 = t18 * t18;
  t46 = 0.1e1 / t20 / t19;
  t49 = 0.1e1 - 0.25e2 / 0.81e2 * t42 * t43 * t46;
  t50 = t49 * t49;
  t51 = t50 * t49;
  t53 = t19 * t19;
  t54 = 0.1e1 / t53;
  t57 = t42 * t42;
  t60 = t53 * t53;
  t61 = 0.1e1 / t60;
  t64 = 0.1e1 + 0.250e3 / 0.243e3 * t42 * t41 * t54 + 0.62500e5 / 0.59049e5 * params->b * t57 * t42 * t61;
  t65 = 0.1e1 / t64;
  t66 = t51 * t65;
  t67 = params->kappa + t31 + params->c;
  t72 = params->kappa * (0.1e1 - params->kappa / t67) - t36;
  t74 = t66 * t72 + t36 + 0.1e1;
  t75 = t17 * t74;
  t79 = my_piecewise3(t3, 0, -0.3e1 / 0.4e1 * t9 * t14 * t75);
  t80 = rho[1] <= t2;
  t81 = rho[1] * t13;
  t82 = rho[1] * t15;
  t83 = POW_1_3(t82);
  t84 = rho[1] * rho[1];
  t85 = POW_1_3(rho[1]);
  t86 = t85 * t85;
  t88 = 0.1e1 / t86 / t84;
  t89 = sigma[2] * t88;
  t91 = 0.5e1 / 0.972e3 * t23 * t89;
  t92 = params->kappa + t91;
  t96 = params->kappa * (0.1e1 - params->kappa / t92);
  t98 = 0.1e1 / t86 / rho[1];
  t101 = tau[1] * t98 - t89 / 0.8e1;
  t102 = t101 * t101;
  t106 = 0.1e1 - 0.25e2 / 0.81e2 * t102 * t43 * t46;
  t107 = t106 * t106;
  t108 = t107 * t106;
  t112 = t102 * t102;
  t117 = 0.1e1 + 0.250e3 / 0.243e3 * t102 * t101 * t54 + 0.62500e5 / 0.59049e5 * params->b * t112 * t102 * t61;
  t118 = 0.1e1 / t117;
  t119 = t108 * t118;
  t120 = params->kappa + t91 + params->c;
  t125 = params->kappa * (0.1e1 - params->kappa / t120) - t96;
  t127 = t119 * t125 + t96 + 0.1e1;
  t128 = t83 * t127;
  t132 = my_piecewise3(t80, 0, -0.3e1 / 0.4e1 * t9 * t81 * t128);
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    zk[0] = t79 + t132;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  t133 = t13 * t17;
  t138 = 0.1e1 / t12 / t10;
  t139 = rho[0] * t138;
  t142 = t9 * t139 * t75 / 0.2e1;
  t144 = t7 * t8 * rho[0];
  t145 = t17 * t17;
  t146 = 0.1e1 / t145;
  t147 = t13 * t146;
  t148 = t10 * t10;
  t149 = 0.1e1 / t148;
  t151 = -rho[0] * t149 + t15;
  t152 = t74 * t151;
  t153 = t147 * t152;
  t156 = params->kappa * params->kappa;
  t157 = t32 * t32;
  t159 = t156 / t157;
  t160 = t159 * t18;
  t161 = t22 * sigma[0];
  t162 = t24 * rho[0];
  t164 = 0.1e1 / t26 / t162;
  t165 = t161 * t164;
  t166 = t160 * t165;
  t168 = t50 * t65;
  t169 = t168 * t72;
  t170 = t41 * t43;
  t175 = -0.5e1 / 0.3e1 * tau[0] * t28 + sigma[0] * t164 / 0.3e1;
  t177 = t170 * t46 * t175;
  t180 = t64 * t64;
  t181 = 0.1e1 / t180;
  t182 = t51 * t181;
  t183 = t42 * t54;
  t187 = params->b * t57 * t41;
  t191 = 0.250e3 / 0.81e2 * t183 * t175 + 0.125000e6 / 0.19683e5 * t187 * t61 * t175;
  t194 = t67 * t67;
  t196 = t156 / t194;
  t197 = t196 * t18;
  t200 = -0.10e2 / 0.729e3 * t197 * t165 + 0.10e2 / 0.729e3 * t166;
  t202 = -0.10e2 / 0.729e3 * t166 - 0.50e2 / 0.27e2 * t169 * t177 - t182 * t72 * t191 + t66 * t200;
  t203 = t17 * t202;
  t208 = my_piecewise3(t3, 0, -0.3e1 / 0.4e1 * t9 * t133 * t74 + t142 - t144 * t153 / 0.4e1 - 0.3e1 / 0.4e1 * t9 * t14 * t203);
  t209 = rho[1] * t138;
  t212 = t9 * t209 * t128 / 0.2e1;
  t214 = 0.1e1 / t12 / t148;
  t215 = t84 * t214;
  t216 = t83 * t83;
  t217 = 0.1e1 / t216;
  t218 = t217 * t127;
  t223 = my_piecewise3(t80, 0, t212 + t9 * t215 * t218 / 0.4e1);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = t79 + t132 + t10 * (t208 + t223);

  t226 = t24 * t214;
  t227 = t146 * t74;
  t232 = my_piecewise3(t3, 0, t142 + t9 * t226 * t227 / 0.4e1);
  t233 = t13 * t83;
  t238 = t7 * t8 * rho[1];
  t239 = t13 * t217;
  t241 = -rho[1] * t149 + t15;
  t242 = t127 * t241;
  t243 = t239 * t242;
  t246 = t92 * t92;
  t248 = t156 / t246;
  t249 = t248 * t18;
  t250 = t22 * sigma[2];
  t251 = t84 * rho[1];
  t253 = 0.1e1 / t86 / t251;
  t254 = t250 * t253;
  t255 = t249 * t254;
  t257 = t107 * t118;
  t258 = t257 * t125;
  t259 = t101 * t43;
  t264 = -0.5e1 / 0.3e1 * tau[1] * t88 + sigma[2] * t253 / 0.3e1;
  t266 = t259 * t46 * t264;
  t269 = t117 * t117;
  t270 = 0.1e1 / t269;
  t271 = t108 * t270;
  t272 = t102 * t54;
  t276 = params->b * t112 * t101;
  t280 = 0.250e3 / 0.81e2 * t272 * t264 + 0.125000e6 / 0.19683e5 * t276 * t61 * t264;
  t283 = t120 * t120;
  t285 = t156 / t283;
  t286 = t285 * t18;
  t289 = -0.10e2 / 0.729e3 * t286 * t254 + 0.10e2 / 0.729e3 * t255;
  t291 = -0.10e2 / 0.729e3 * t255 - 0.50e2 / 0.27e2 * t258 * t266 - t271 * t125 * t280 + t119 * t289;
  t292 = t83 * t291;
  t297 = my_piecewise3(t80, 0, -0.3e1 / 0.4e1 * t9 * t233 * t127 + t212 - t238 * t243 / 0.4e1 - 0.3e1 / 0.4e1 * t9 * t81 * t292);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[1] = t79 + t132 + t10 * (t232 + t297);

  t300 = t23 * t28;
  t301 = t159 * t300;
  t303 = t46 * t28;
  t304 = t170 * t303;
  t305 = t169 * t304;
  t307 = t183 * t28;
  t309 = t61 * t28;
  t310 = t187 * t309;
  t312 = -0.125e3 / 0.324e3 * t307 - 0.15625e5 / 0.19683e5 * t310;
  t313 = t72 * t312;
  t317 = 0.5e1 / 0.972e3 * t196 * t300 - 0.5e1 / 0.972e3 * t301;
  t319 = 0.5e1 / 0.972e3 * t301 + 0.25e2 / 0.108e3 * t305 - t182 * t313 + t66 * t317;
  t320 = t17 * t319;
  t324 = my_piecewise3(t3, 0, -0.3e1 / 0.4e1 * t9 * t14 * t320);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[0] = t10 * t324;

  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[1] = 0.0e0;

  t325 = t23 * t88;
  t326 = t248 * t325;
  t328 = t46 * t88;
  t329 = t259 * t328;
  t330 = t258 * t329;
  t332 = t272 * t88;
  t334 = t61 * t88;
  t335 = t276 * t334;
  t337 = -0.125e3 / 0.324e3 * t332 - 0.15625e5 / 0.19683e5 * t335;
  t338 = t125 * t337;
  t342 = 0.5e1 / 0.972e3 * t285 * t325 - 0.5e1 / 0.972e3 * t326;
  t344 = 0.5e1 / 0.972e3 * t326 + 0.25e2 / 0.108e3 * t330 - t271 * t338 + t119 * t342;
  t345 = t83 * t344;
  t349 = my_piecewise3(t80, 0, -0.3e1 / 0.4e1 * t9 * t81 * t345);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[2] = t10 * t349;

  if(vrho != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vlapl[0] = 0.0e0;

  if(vrho != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vlapl[1] = 0.0e0;

  t350 = t46 * t38;
  t351 = t170 * t350;
  t356 = t61 * t38;
  t359 = 0.250e3 / 0.81e2 * t183 * t38 + 0.125000e6 / 0.19683e5 * t187 * t356;
  t360 = t72 * t359;
  t362 = -0.50e2 / 0.27e2 * t169 * t351 - t182 * t360;
  t363 = t17 * t362;
  t367 = my_piecewise3(t3, 0, -0.3e1 / 0.4e1 * t9 * t14 * t363);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vtau[0] = t10 * t367;

  t368 = t46 * t98;
  t369 = t259 * t368;
  t374 = t61 * t98;
  t377 = 0.250e3 / 0.81e2 * t272 * t98 + 0.125000e6 / 0.19683e5 * t276 * t374;
  t378 = t125 * t377;
  t380 = -0.50e2 / 0.27e2 * t258 * t369 - t271 * t378;
  t381 = t83 * t380;
  t385 = my_piecewise3(t80, 0, -0.3e1 / 0.4e1 * t9 * t81 * t381);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vtau[1] = t10 * t385;

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t390 = t9 * t138 * t17 * t74;
  t396 = rho[0] * t214;
  t399 = 0.5e1 / 0.6e1 * t9 * t396 * t75;
  t402 = t144 * t138 * t146 * t152;
  t405 = t9 * t139 * t203;
  t407 = 0.1e1 / t145 / t16;
  t409 = t151 * t151;
  t418 = t148 * t10;
  t419 = 0.1e1 / t418;
  t429 = t156 / t157 / t32;
  t430 = t429 * t43;
  t431 = sigma[0] * sigma[0];
  t433 = t24 * t24;
  t437 = t46 * t431 / t25 / t433 / t162;
  t439 = 0.200e3 / 0.531441e6 * t430 * t437;
  t441 = 0.1e1 / t26 / t433;
  t442 = t161 * t441;
  t444 = 0.110e3 / 0.2187e4 * t160 * t442;
  t445 = t49 * t65;
  t446 = t445 * t72;
  t447 = t42 * t18;
  t449 = 0.1e1 / t21 / t53;
  t450 = t175 * t175;
  t455 = t50 * t181;
  t457 = t455 * t72 * t41;
  t458 = t43 * t46;
  t463 = t168 * t200;
  t474 = 0.40e2 / 0.9e1 * tau[0] * t164 - 0.11e2 / 0.9e1 * sigma[0] * t441;
  t481 = t51 / t180 / t64;
  t482 = t191 * t191;
  t489 = t41 * t54;
  t494 = params->b * t57;
  t506 = t156 / t194 / t67;
  t507 = t506 * t43;
  t514 = -t439 + t444 + 0.10000e5 / 0.729e3 * t446 * t447 * t449 * t450 + 0.100e3 / 0.27e2 * t457 * t458 * t175 * t191 - 0.100e3 / 0.27e2 * t463 * t177 - 0.50e2 / 0.27e2 * t169 * t450 * t43 * t46 - 0.50e2 / 0.27e2 * t169 * t170 * t46 * t474 + 0.2e1 * t481 * t72 * t482 - 0.2e1 * t182 * t200 * t191 - t182 * t72 * (0.500e3 / 0.81e2 * t489 * t450 + 0.250e3 / 0.81e2 * t183 * t474 + 0.625000e6 / 0.19683e5 * t494 * t61 * t450 + 0.125000e6 / 0.19683e5 * t187 * t61 * t474) + t66 * (-0.200e3 / 0.531441e6 * t507 * t437 + 0.110e3 / 0.2187e4 * t197 * t442 + t439 - t444);
  t520 = my_piecewise3(t3, 0, t390 - t9 * t153 / 0.2e1 - 0.3e1 / 0.2e1 * t9 * t133 * t202 - t399 + t402 / 0.3e1 + t405 + t144 * t13 * t407 * t74 * t409 / 0.6e1 - t144 * t147 * t202 * t151 / 0.2e1 - t144 * t147 * t74 * (0.2e1 * rho[0] * t419 - 0.2e1 * t149) / 0.4e1 - 0.3e1 / 0.4e1 * t9 * t14 * t17 * t514);
  t524 = 0.5e1 / 0.6e1 * t9 * rho[1] * t214 * t128;
  t526 = 0.1e1 / t12 / t418;
  t529 = t9 * t84 * t526 * t218;
  t531 = t148 * t148;
  t533 = 0.1e1 / t12 / t531;
  t536 = 0.1e1 / t216 / t82;
  t542 = my_piecewise3(t80, 0, -t524 - 0.5e1 / 0.6e1 * t529 + t9 * t251 * t533 * t536 * t127 / 0.6e1);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = 0.2e1 * t208 + 0.2e1 * t223 + t10 * (t520 + t542);

  t553 = t9 * t24 * t526 * t227;
  t566 = my_piecewise3(t3, 0, t390 / 0.2e1 - t399 + t402 / 0.6e1 + t405 / 0.2e1 + t9 * t396 * t227 / 0.2e1 - 0.2e1 / 0.3e1 * t553 - t7 * t8 * t24 * t214 * t407 * t152 / 0.6e1 + t9 * t226 * t146 * t202 / 0.4e1);
  t569 = t9 * t138 * t83 * t127;
  t579 = t238 * t138 * t217 * t242;
  t587 = rho[1] * t419;
  t595 = t9 * t209 * t292;
  t602 = my_piecewise3(t80, 0, t569 / 0.2e1 + t9 * t214 * t217 * t127 * rho[1] / 0.4e1 - t524 - t529 / 0.6e1 + t579 / 0.6e1 - t7 * t8 * t84 * t214 * t536 * t242 / 0.6e1 - t238 * t239 * t127 * (-t149 + 0.2e1 * t587) / 0.4e1 + t595 / 0.2e1 + t9 * t215 * t217 * t291 / 0.4e1);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[1] = t208 + t223 + t232 + t297 + t10 * (t566 + t602);

  t614 = my_piecewise3(t3, 0, -t399 - 0.5e1 / 0.6e1 * t553 + t9 * t162 * t533 * t407 * t74 / 0.6e1);
  t622 = t241 * t241;
  t639 = t156 / t246 / t92;
  t640 = t639 * t43;
  t641 = sigma[2] * sigma[2];
  t643 = t84 * t84;
  t647 = t46 * t641 / t85 / t643 / t251;
  t649 = 0.200e3 / 0.531441e6 * t640 * t647;
  t651 = 0.1e1 / t86 / t643;
  t652 = t250 * t651;
  t654 = 0.110e3 / 0.2187e4 * t249 * t652;
  t655 = t106 * t118;
  t656 = t655 * t125;
  t657 = t102 * t18;
  t658 = t264 * t264;
  t663 = t107 * t270;
  t665 = t663 * t125 * t101;
  t670 = t257 * t289;
  t681 = 0.40e2 / 0.9e1 * tau[1] * t253 - 0.11e2 / 0.9e1 * sigma[2] * t651;
  t688 = t108 / t269 / t117;
  t689 = t280 * t280;
  t696 = t101 * t54;
  t701 = params->b * t112;
  t713 = t156 / t283 / t120;
  t714 = t713 * t43;
  t721 = -t649 + t654 + 0.10000e5 / 0.729e3 * t656 * t657 * t449 * t658 + 0.100e3 / 0.27e2 * t665 * t458 * t264 * t280 - 0.100e3 / 0.27e2 * t670 * t266 - 0.50e2 / 0.27e2 * t258 * t658 * t43 * t46 - 0.50e2 / 0.27e2 * t258 * t259 * t46 * t681 + 0.2e1 * t688 * t125 * t689 - 0.2e1 * t271 * t289 * t280 - t271 * t125 * (0.500e3 / 0.81e2 * t696 * t658 + 0.250e3 / 0.81e2 * t272 * t681 + 0.625000e6 / 0.19683e5 * t701 * t61 * t658 + 0.125000e6 / 0.19683e5 * t276 * t61 * t681) + t119 * (-0.200e3 / 0.531441e6 * t714 * t647 + 0.110e3 / 0.2187e4 * t286 * t652 + t649 - t654);
  t727 = my_piecewise3(t80, 0, t569 - t9 * t243 / 0.2e1 - 0.3e1 / 0.2e1 * t9 * t233 * t291 - t524 + t579 / 0.3e1 + t595 + t238 * t13 * t536 * t127 * t622 / 0.6e1 - t238 * t239 * t291 * t241 / 0.2e1 - t238 * t239 * t127 * (-0.2e1 * t149 + 0.2e1 * t587) / 0.4e1 - 0.3e1 / 0.4e1 * t9 * t81 * t83 * t721);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[2] = 0.2e1 * t232 + 0.2e1 * t297 + t10 * (t614 + t727);

  t735 = t9 * t139 * t320 / 0.2e1;
  t744 = t46 / t25 / t433 / t24 * sigma[0];
  t746 = 0.25e2 / 0.177147e6 * t430 * t744;
  t747 = t23 * t164;
  t749 = 0.10e2 / 0.729e3 * t159 * t747;
  t751 = t445 * t72 * t42;
  t752 = t18 * t449;
  t753 = t28 * t175;
  t763 = t175 * t43;
  t792 = t168 * t317;
  t803 = t746 - t749 - 0.1250e4 / 0.729e3 * t751 * t752 * t753 - 0.25e2 / 0.108e3 * t457 * t458 * t28 * t191 + 0.25e2 / 0.108e3 * t463 * t304 + 0.25e2 / 0.108e3 * t169 * t763 * t303 - 0.50e2 / 0.81e2 * t169 * t170 * t46 * t164 + 0.50e2 / 0.27e2 * t455 * t313 * t177 + 0.2e1 * t481 * t313 * t191 - t182 * t200 * t312 - t182 * t72 * (-0.125e3 / 0.162e3 * t489 * t753 + 0.250e3 / 0.243e3 * t183 * t164 - 0.78125e5 / 0.19683e5 * t494 * t309 * t175 + 0.125000e6 / 0.59049e5 * t187 * t61 * t164) - 0.50e2 / 0.27e2 * t792 * t177 - t182 * t317 * t191 + t66 * (0.25e2 / 0.177147e6 * t507 * t744 - 0.10e2 / 0.729e3 * t196 * t747 - t746 + t749);
  t809 = my_piecewise3(t3, 0, -0.3e1 / 0.4e1 * t9 * t133 * t319 + t735 - t144 * t147 * t319 * t151 / 0.4e1 - 0.3e1 / 0.4e1 * t9 * t14 * t17 * t803);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[0] = t10 * t809 + t324;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[1] = 0.0e0;

  t813 = t9 * t209 * t345 / 0.2e1;
  t819 = my_piecewise3(t80, 0, t813 + t9 * t215 * t217 * t344 / 0.4e1);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[2] = t10 * t819 + t349;

  t826 = my_piecewise3(t3, 0, t735 + t9 * t226 * t146 * t319 / 0.4e1);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[3] = t10 * t826 + t324;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[4] = 0.0e0;

  t839 = t46 / t85 / t643 / t84 * sigma[2];
  t841 = 0.25e2 / 0.177147e6 * t640 * t839;
  t842 = t23 * t253;
  t844 = 0.10e2 / 0.729e3 * t248 * t842;
  t846 = t655 * t125 * t102;
  t847 = t88 * t264;
  t857 = t264 * t43;
  t886 = t257 * t342;
  t897 = t841 - t844 - 0.1250e4 / 0.729e3 * t846 * t752 * t847 - 0.25e2 / 0.108e3 * t665 * t458 * t88 * t280 + 0.25e2 / 0.108e3 * t670 * t329 + 0.25e2 / 0.108e3 * t258 * t857 * t328 - 0.50e2 / 0.81e2 * t258 * t259 * t46 * t253 + 0.50e2 / 0.27e2 * t663 * t338 * t266 + 0.2e1 * t688 * t338 * t280 - t271 * t289 * t337 - t271 * t125 * (-0.125e3 / 0.162e3 * t696 * t847 + 0.250e3 / 0.243e3 * t272 * t253 - 0.78125e5 / 0.19683e5 * t701 * t334 * t264 + 0.125000e6 / 0.59049e5 * t276 * t61 * t253) - 0.50e2 / 0.27e2 * t886 * t266 - t271 * t342 * t280 + t119 * (0.25e2 / 0.177147e6 * t714 * t839 - 0.10e2 / 0.729e3 * t285 * t842 - t841 + t844);
  t903 = my_piecewise3(t80, 0, -0.3e1 / 0.4e1 * t9 * t233 * t344 + t813 - t238 * t239 * t344 * t241 / 0.4e1 - 0.3e1 / 0.4e1 * t9 * t81 * t83 * t897);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[5] = t10 * t903 + t349;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rholapl[0] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rholapl[1] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rholapl[2] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rholapl[3] = 0.0e0;

  t910 = t9 * t139 * t363 / 0.2e1;
  t915 = t38 * t175;
  t929 = t455 * t360;
  t953 = my_piecewise3(t3, 0, -0.3e1 / 0.4e1 * t9 * t133 * t362 + t910 - t144 * t147 * t362 * t151 / 0.4e1 - 0.3e1 / 0.4e1 * t9 * t14 * t17 * (0.10000e5 / 0.729e3 * t751 * t752 * t915 + 0.50e2 / 0.27e2 * t457 * t458 * t38 * t191 - 0.50e2 / 0.27e2 * t463 * t351 - 0.50e2 / 0.27e2 * t169 * t763 * t350 + 0.250e3 / 0.81e2 * t305 + 0.50e2 / 0.27e2 * t929 * t177 + 0.2e1 * t481 * t360 * t191 - t182 * t200 * t359 - t182 * t72 * (0.500e3 / 0.81e2 * t489 * t915 - 0.1250e4 / 0.243e3 * t307 + 0.625000e6 / 0.19683e5 * t494 * t356 * t175 - 0.625000e6 / 0.59049e5 * t310)));
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhotau[0] = t10 * t953 + t367;

  t957 = t9 * t209 * t381 / 0.2e1;
  t963 = my_piecewise3(t80, 0, t957 + t9 * t215 * t217 * t380 / 0.4e1);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhotau[1] = t10 * t963 + t385;

  t970 = my_piecewise3(t3, 0, t910 + t9 * t226 * t146 * t362 / 0.4e1);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhotau[2] = t10 * t970 + t367;

  t979 = t98 * t264;
  t993 = t663 * t378;
  t1017 = my_piecewise3(t80, 0, -0.3e1 / 0.4e1 * t9 * t233 * t380 + t957 - t238 * t239 * t380 * t241 / 0.4e1 - 0.3e1 / 0.4e1 * t9 * t81 * t83 * (0.10000e5 / 0.729e3 * t846 * t752 * t979 + 0.50e2 / 0.27e2 * t665 * t458 * t98 * t280 - 0.50e2 / 0.27e2 * t670 * t369 - 0.50e2 / 0.27e2 * t258 * t857 * t368 + 0.250e3 / 0.81e2 * t330 + 0.50e2 / 0.27e2 * t993 * t266 + 0.2e1 * t688 * t378 * t280 - t271 * t289 * t377 - t271 * t125 * (0.500e3 / 0.81e2 * t696 * t979 - 0.1250e4 / 0.243e3 * t332 + 0.625000e6 / 0.19683e5 * t701 * t374 * t264 - 0.625000e6 / 0.59049e5 * t335)));
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhotau[3] = t10 * t1017 + t385;

  t1021 = 0.1e1 / t25 / t433 / rho[0];
  t1022 = t458 * t1021;
  t1023 = t429 * t1022;
  t1037 = t312 * t312;
  t1061 = my_piecewise3(t3, 0, -0.3e1 / 0.4e1 * t9 * t14 * t17 * (-0.25e2 / 0.472392e6 * t1023 + 0.625e3 / 0.2916e4 * t446 * t447 * t449 * t1021 - 0.25e2 / 0.54e2 * t457 * t458 * t28 * t312 + 0.25e2 / 0.54e2 * t792 * t304 - 0.25e2 / 0.864e3 * t169 * t1022 + 0.2e1 * t481 * t72 * t1037 - 0.2e1 * t182 * t317 * t312 - t182 * t72 * (0.125e3 / 0.1296e4 * t489 * t1021 + 0.78125e5 / 0.157464e6 * t494 * t61 * t1021) + t66 * (-0.25e2 / 0.472392e6 * t506 * t1022 + 0.25e2 / 0.472392e6 * t1023)));
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[0] = t10 * t1061;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[1] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[2] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[3] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[4] = 0.0e0;

  t1064 = 0.1e1 / t85 / t643 / rho[1];
  t1065 = t458 * t1064;
  t1066 = t639 * t1065;
  t1080 = t337 * t337;
  t1104 = my_piecewise3(t80, 0, -0.3e1 / 0.4e1 * t9 * t81 * t83 * (-0.25e2 / 0.472392e6 * t1066 + 0.625e3 / 0.2916e4 * t656 * t657 * t449 * t1064 - 0.25e2 / 0.54e2 * t665 * t458 * t88 * t337 + 0.25e2 / 0.54e2 * t886 * t329 - 0.25e2 / 0.864e3 * t258 * t1065 + 0.2e1 * t688 * t125 * t1080 - 0.2e1 * t271 * t342 * t337 - t271 * t125 * (0.125e3 / 0.1296e4 * t696 * t1064 + 0.78125e5 / 0.157464e6 * t701 * t61 * t1064) + t119 * (-0.25e2 / 0.472392e6 * t713 * t1065 + 0.25e2 / 0.472392e6 * t1066)));
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[5] = t10 * t1104;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmalapl[0] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmalapl[1] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmalapl[2] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmalapl[3] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmalapl[4] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmalapl[5] = 0.0e0;

  t1106 = 0.1e1 / t25 / t433;
  t1141 = my_piecewise3(t3, 0, -0.3e1 / 0.4e1 * t9 * t14 * t17 * (-0.1250e4 / 0.729e3 * t446 * t447 * t449 * t1106 + 0.50e2 / 0.27e2 * t457 * t458 * t38 * t312 - 0.50e2 / 0.27e2 * t792 * t351 + 0.25e2 / 0.108e3 * t169 * t1106 * t43 * t46 - 0.25e2 / 0.108e3 * t929 * t304 + 0.2e1 * t481 * t360 * t312 - t182 * t317 * t359 - t182 * t72 * (-0.125e3 / 0.162e3 * t489 * t1106 - 0.78125e5 / 0.19683e5 * t494 * t61 * t1106)));
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmatau[0] = t10 * t1141;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmatau[1] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmatau[2] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmatau[3] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmatau[4] = 0.0e0;

  t1143 = 0.1e1 / t85 / t643;
  t1178 = my_piecewise3(t80, 0, -0.3e1 / 0.4e1 * t9 * t81 * t83 * (-0.1250e4 / 0.729e3 * t656 * t657 * t449 * t1143 + 0.50e2 / 0.27e2 * t665 * t458 * t98 * t337 - 0.50e2 / 0.27e2 * t886 * t369 + 0.25e2 / 0.108e3 * t258 * t1143 * t43 * t46 - 0.25e2 / 0.108e3 * t993 * t329 + 0.2e1 * t688 * t378 * t337 - t271 * t342 * t377 - t271 * t125 * (-0.125e3 / 0.162e3 * t696 * t1143 - 0.78125e5 / 0.19683e5 * t701 * t61 * t1143)));
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigmatau[5] = t10 * t1178;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2lapl2[0] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2lapl2[1] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2lapl2[2] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2lapltau[0] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2lapltau[1] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2lapltau[2] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_NEEDS_LAPLACIAN) && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2lapltau[3] = 0.0e0;

  t1180 = 0.1e1 / t25 / t162;
  t1193 = t359 * t359;
  t1210 = my_piecewise3(t3, 0, -0.3e1 / 0.4e1 * t9 * t14 * t17 * (0.10000e5 / 0.729e3 * t446 * t447 * t449 * t1180 + 0.100e3 / 0.27e2 * t457 * t458 * t38 * t359 - 0.50e2 / 0.27e2 * t169 * t1180 * t43 * t46 + 0.2e1 * t481 * t72 * t1193 - t182 * t72 * (0.500e3 / 0.81e2 * t489 * t1180 + 0.625000e6 / 0.19683e5 * t494 * t61 * t1180)));
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2tau2[0] = t10 * t1210;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2tau2[1] = 0.0e0;

  t1212 = 0.1e1 / t85 / t251;
  t1225 = t377 * t377;
  t1242 = my_piecewise3(t80, 0, -0.3e1 / 0.4e1 * t9 * t81 * t83 * (0.10000e5 / 0.729e3 * t656 * t657 * t449 * t1212 + 0.100e3 / 0.27e2 * t665 * t458 * t98 * t377 - 0.50e2 / 0.27e2 * t258 * t1212 * t43 * t46 + 0.2e1 * t688 * t125 * t1225 - t271 * t125 * (0.500e3 / 0.81e2 * t696 * t1212 + 0.625000e6 / 0.19683e5 * t701 * t61 * t1212)));
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2tau2[2] = t10 * t1242;

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


#endif

#endif

#endif


}

