/* 
  This file was generated automatically with ./scripts/maple2c.pl.
  Do not edit this file directly as it can be overwritten!!

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Maple version     : Maple 2016 (X86 64 LINUX)
  Maple source      : ./maple/gga_exc/gga_x_2d_b86_mgc.mpl
  Type of functional: gga_exc
*/

#define maple2c_order 2
#define MAPLE2C_FLAGS (XC_FLAGS_I_HAVE_EXC | XC_FLAGS_I_HAVE_VXC | XC_FLAGS_I_HAVE_FXC)


static inline void
func_unpol(const xc_func_type *p, int order, const double *rho, const double *sigma , double *zk GGA_OUT_PARAMS_NO_EXC(XC_COMMA double *, ))
{

#ifndef XC_DONT_COMPILE_EXC
  double t3, t4, t6, t7, t8, t9, t10, t11;
  double t12, t14, t15, t16, t17, t18, t21, t25;

#ifndef XC_DONT_COMPILE_VXC
  double t26, t30, t31, t35, t37, t40, t43, t48;
  double t54, t58, t62;

#ifndef XC_DONT_COMPILE_FXC
  double t78, t87, t89, t97, t118, t132;
#endif

#endif

#endif



  t3 = rho[0] / 0.2e1 <= 0.101e1 * p->threshold_dens;
  t4 = sqrt(M_PI);
  t6 = M_SQRT2;
  t7 = 0.1e1 / t4 * t6;
  t8 = sqrt(rho[0]);
  t9 = rho[0] * rho[0];
  t10 = t9 * rho[0];
  t11 = 0.1e1 / t10;
  t12 = sigma[0] * t11;
  t14 = 0.1e1 + 0.16646e-1 * t12;
  t15 = POW_1_4(t14);
  t16 = t15 * t15;
  t17 = t16 * t15;
  t18 = 0.1e1 / t17;
  t21 = 0.1e1 + 0.44094220675901974970e-2 * t12 * t18;
  t25 = my_piecewise3(t3, 0, -0.2e1 / 0.3e1 * t7 * t8 * t21);
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    zk[0] = 0.2e1 * t25;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  t26 = 0.1e1 / t8;
  t30 = t9 * t9;
  t31 = 0.1e1 / t30;
  t35 = sigma[0] * sigma[0];
  t37 = 0.1e1 / t30 / t10;
  t40 = 0.1e1 / t17 / t14;
  t43 = -0.13228266202770592491e-1 * sigma[0] * t31 * t18 + 0.16514828940848946195e-3 * t35 * t37 * t40;
  t48 = my_piecewise3(t3, 0, -t7 * t26 * t21 / 0.3e1 - 0.2e1 / 0.3e1 * t7 * t8 * t43);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = 0.2e1 * rho[0] * t48 + 0.2e1 * t25;

  t54 = 0.1e1 / t30 / t9;
  t58 = 0.44094220675901974970e-2 * t11 * t18 - 0.55049429802829820651e-4 * sigma[0] * t54 * t40;
  t62 = my_piecewise3(t3, 0, -0.2e1 / 0.3e1 * t7 * t8 * t58);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[0] = 0.2e1 * rho[0] * t62;

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t78 = t30 * t30;
  t87 = t14 * t14;
  t89 = 0.1e1 / t17 / t87;
  t97 = my_piecewise3(t3, 0, t7 / t8 / rho[0] * t21 / 0.6e1 - 0.2e1 / 0.3e1 * t7 * t26 * t43 - 0.2e1 / 0.3e1 * t7 * t8 * (0.52913064811082369964e-1 * sigma[0] / t30 / rho[0] * t18 - 0.16514828940848946195e-2 * t35 / t78 * t40 + 0.14432556733842006814e-4 * t35 * sigma[0] / t78 / t10 * t89));
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = 0.2e1 * rho[0] * t97 + 0.4e1 * t48;

  t118 = my_piecewise3(t3, 0, -t7 * t26 * t58 / 0.3e1 - 0.2e1 / 0.3e1 * t7 * t8 * (-0.13228266202770592491e-1 * t31 * t18 + 0.49544486822546838586e-3 * t37 * t40 * sigma[0] - 0.48108522446140022714e-5 * t35 / t78 / t9 * t89));
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[0] = 0.2e1 * rho[0] * t118 + 0.2e1 * t62;

  t132 = my_piecewise3(t3, 0, -0.2e1 / 0.3e1 * t7 * t8 * (-0.11009885960565964130e-3 * t54 * t40 + 0.16036174148713340905e-5 * sigma[0] / t78 / rho[0] * t89));
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[0] = 0.2e1 * rho[0] * t132;

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


#endif

#endif

#endif


}


static inline void
func_pol(const xc_func_type *p, int order, const double *rho, const double *sigma , double *zk GGA_OUT_PARAMS_NO_EXC(XC_COMMA double *, ))
{

#ifndef XC_DONT_COMPILE_EXC
  double t1, t2, t3, t4, t5, t6, t7, t8;
  double t9, t10, t11, t12, t13, t14, t15, t16;
  double t18, t19, t20, t21, t22, t25, t29, t30;
  double t31, t32, t33, t34, t35, t36, t37, t38;
  double t40, t41, t42, t43, t44, t47, t51;

#ifndef XC_DONT_COMPILE_VXC
  double t52, t53, t57, t58, t60, t62, t63, t64;
  double t65, t66, t68, t69, t72, t73, t77, t79;
  double t82, t85, t90, t91, t93, t94, t96, t97;
  double t98, t103, t106, t107, t108, t112, t113, t117;
  double t118, t120, t121, t124, t125, t129, t131, t134;
  double t137, t142, t148, t152, t156, t160, t164, t168;

#ifndef XC_DONT_COMPILE_FXC
  double t171, t172, t182, t184, t187, t190, t191, t192;
  double t200, t201, t213, t222, t224, t232, t236, t238;
  double t241, t244, t246, t248, t254, t264, t274, t275;
  double t283, t286, t290, t297, t303, t315, t324, t342;
  double t351, t353, t361, t368, t389, t392, t397, t403;
  double t428, t441, t453;
#endif

#endif

#endif



  t1 = 0.101e1 * p->threshold_dens;
  t2 = rho[0] <= t1;
  t3 = sqrt(M_PI);
  t4 = 0.1e1 / t3;
  t5 = t4 * rho[0];
  t6 = rho[0] + rho[1];
  t7 = sqrt(t6);
  t8 = 0.1e1 / t7;
  t9 = 0.1e1 / t6;
  t10 = rho[0] * t9;
  t11 = sqrt(t10);
  t12 = t8 * t11;
  t13 = rho[0] * rho[0];
  t14 = t13 * rho[0];
  t15 = 0.1e1 / t14;
  t16 = sigma[0] * t15;
  t18 = 0.1e1 + 0.8323e-2 * t16;
  t19 = POW_1_4(t18);
  t20 = t19 * t19;
  t21 = t20 * t19;
  t22 = 0.1e1 / t21;
  t25 = 0.1e1 + 0.22047110337950987485e-2 * t16 * t22;
  t29 = my_piecewise3(t2, 0, -0.8e1 / 0.3e1 * t5 * t12 * t25);
  t30 = rho[1] <= t1;
  t31 = t4 * rho[1];
  t32 = rho[1] * t9;
  t33 = sqrt(t32);
  t34 = t8 * t33;
  t35 = rho[1] * rho[1];
  t36 = t35 * rho[1];
  t37 = 0.1e1 / t36;
  t38 = sigma[2] * t37;
  t40 = 0.1e1 + 0.8323e-2 * t38;
  t41 = POW_1_4(t40);
  t42 = t41 * t41;
  t43 = t42 * t41;
  t44 = 0.1e1 / t43;
  t47 = 0.1e1 + 0.22047110337950987485e-2 * t38 * t44;
  t51 = my_piecewise3(t30, 0, -0.8e1 / 0.3e1 * t31 * t34 * t47);
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    zk[0] = t29 + t51;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  t52 = t4 * t8;
  t53 = t11 * t25;
  t57 = 0.1e1 / t7 / t6;
  t58 = t57 * t11;
  t60 = t5 * t58 * t25;
  t62 = t5 * t8;
  t63 = 0.1e1 / t11;
  t64 = t63 * t25;
  t65 = t6 * t6;
  t66 = 0.1e1 / t65;
  t68 = -rho[0] * t66 + t9;
  t69 = t64 * t68;
  t72 = t13 * t13;
  t73 = 0.1e1 / t72;
  t77 = sigma[0] * sigma[0];
  t79 = 0.1e1 / t72 / t14;
  t82 = 0.1e1 / t21 / t18;
  t85 = -0.66141331013852962455e-2 * sigma[0] * t73 * t22 + 0.41287072352122365488e-4 * t77 * t79 * t82;
  t90 = my_piecewise3(t2, 0, -0.8e1 / 0.3e1 * t52 * t53 + 0.4e1 / 0.3e1 * t60 - 0.4e1 / 0.3e1 * t62 * t69 - 0.8e1 / 0.3e1 * t5 * t12 * t85);
  t91 = t57 * t33;
  t93 = t31 * t91 * t47;
  t94 = t4 * t35;
  t96 = 0.1e1 / t7 / t65;
  t97 = 0.1e1 / t33;
  t98 = t96 * t97;
  t103 = my_piecewise3(t30, 0, 0.4e1 / 0.3e1 * t94 * t98 * t47 + 0.4e1 / 0.3e1 * t93);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = t29 + t51 + t6 * (t90 + t103);

  t106 = t4 * t13;
  t107 = t96 * t63;
  t108 = t107 * t25;
  t112 = my_piecewise3(t2, 0, 0.4e1 / 0.3e1 * t106 * t108 + 0.4e1 / 0.3e1 * t60);
  t113 = t33 * t47;
  t117 = t31 * t8;
  t118 = t97 * t47;
  t120 = -rho[1] * t66 + t9;
  t121 = t118 * t120;
  t124 = t35 * t35;
  t125 = 0.1e1 / t124;
  t129 = sigma[2] * sigma[2];
  t131 = 0.1e1 / t124 / t36;
  t134 = 0.1e1 / t43 / t40;
  t137 = -0.66141331013852962455e-2 * sigma[2] * t125 * t44 + 0.41287072352122365488e-4 * t129 * t131 * t134;
  t142 = my_piecewise3(t30, 0, -0.8e1 / 0.3e1 * t52 * t113 + 0.4e1 / 0.3e1 * t93 - 0.4e1 / 0.3e1 * t117 * t121 - 0.8e1 / 0.3e1 * t31 * t34 * t137);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[1] = t29 + t51 + t6 * (t112 + t142);

  t148 = 0.1e1 / t72 / t13;
  t152 = 0.22047110337950987485e-2 * t15 * t22 - 0.13762357450707455163e-4 * sigma[0] * t148 * t82;
  t156 = my_piecewise3(t2, 0, -0.8e1 / 0.3e1 * t5 * t12 * t152);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[0] = t6 * t156;

  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[1] = 0.0e0;

  t160 = 0.1e1 / t124 / t35;
  t164 = 0.22047110337950987485e-2 * t37 * t44 - 0.13762357450707455163e-4 * sigma[2] * t160 * t134;
  t168 = my_piecewise3(t30, 0, -0.8e1 / 0.3e1 * t31 * t34 * t164);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[2] = t6 * t168;

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t171 = t4 * t57;
  t172 = t171 * t53;
  t182 = 0.2e1 * t5 * t96 * t11 * t25;
  t184 = t5 * t57 * t69;
  t187 = t5 * t58 * t85;
  t190 = 0.1e1 / t11 / t10;
  t191 = t190 * t25;
  t192 = t68 * t68;
  t200 = t65 * t6;
  t201 = 0.1e1 / t200;
  t213 = t72 * t72;
  t222 = t18 * t18;
  t224 = 0.1e1 / t21 / t222;
  t232 = my_piecewise3(t2, 0, 0.8e1 / 0.3e1 * t172 - 0.8e1 / 0.3e1 * t52 * t69 - 0.16e2 / 0.3e1 * t52 * t11 * t85 - t182 + 0.4e1 / 0.3e1 * t184 + 0.8e1 / 0.3e1 * t187 + 0.2e1 / 0.3e1 * t62 * t191 * t192 - 0.8e1 / 0.3e1 * t62 * t63 * t85 * t68 - 0.4e1 / 0.3e1 * t62 * t64 * (0.2e1 * rho[0] * t201 - 0.2e1 * t66) - 0.8e1 / 0.3e1 * t5 * t12 * (0.26456532405541184982e-1 * sigma[0] / t72 / rho[0] * t22 - 0.41287072352122365489e-3 * t77 / t213 * t82 + 0.18040695917302508518e-5 * t77 * sigma[0] / t213 / t14 * t224));
  t236 = 0.2e1 * t31 * t96 * t33 * t47;
  t238 = 0.1e1 / t7 / t200;
  t241 = t94 * t238 * t97 * t47;
  t244 = t65 * t65;
  t246 = 0.1e1 / t7 / t244;
  t248 = 0.1e1 / t33 / t32;
  t254 = my_piecewise3(t30, 0, -t236 - 0.4e1 * t241 + 0.2e1 / 0.3e1 * t4 * t36 * t246 * t248 * t47);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = 0.2e1 * t90 + 0.2e1 * t103 + t6 * (t232 + t254);

  t264 = t106 * t238 * t63 * t25;
  t274 = my_piecewise3(t2, 0, 0.4e1 / 0.3e1 * t172 - t182 + 0.2e1 / 0.3e1 * t184 + 0.4e1 / 0.3e1 * t187 + 0.8e1 / 0.3e1 * t5 * t108 - 0.10e2 / 0.3e1 * t264 - 0.2e1 / 0.3e1 * t106 * t96 * t191 * t68 + 0.4e1 / 0.3e1 * t106 * t107 * t85);
  t275 = t171 * t113;
  t283 = t31 * t57 * t121;
  t286 = t248 * t47;
  t290 = rho[1] * t201;
  t297 = t31 * t91 * t137;
  t303 = my_piecewise3(t30, 0, 0.4e1 / 0.3e1 * t275 + 0.4e1 / 0.3e1 * t4 * t96 * t118 * rho[1] - t236 - 0.2e1 / 0.3e1 * t241 + 0.2e1 / 0.3e1 * t283 - 0.2e1 / 0.3e1 * t94 * t96 * t286 * t120 - 0.4e1 / 0.3e1 * t117 * t118 * (-t66 + 0.2e1 * t290) + 0.4e1 / 0.3e1 * t297 + 0.4e1 / 0.3e1 * t94 * t98 * t137);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[1] = t90 + t103 + t112 + t142 + t6 * (t274 + t303);

  t315 = my_piecewise3(t2, 0, -t182 - 0.4e1 * t264 + 0.2e1 / 0.3e1 * t4 * t14 * t246 * t190 * t25);
  t324 = t120 * t120;
  t342 = t124 * t124;
  t351 = t40 * t40;
  t353 = 0.1e1 / t43 / t351;
  t361 = my_piecewise3(t30, 0, 0.8e1 / 0.3e1 * t275 - 0.8e1 / 0.3e1 * t52 * t121 - 0.16e2 / 0.3e1 * t52 * t33 * t137 - t236 + 0.4e1 / 0.3e1 * t283 + 0.8e1 / 0.3e1 * t297 + 0.2e1 / 0.3e1 * t117 * t286 * t324 - 0.8e1 / 0.3e1 * t117 * t97 * t137 * t120 - 0.4e1 / 0.3e1 * t117 * t118 * (-0.2e1 * t66 + 0.2e1 * t290) - 0.8e1 / 0.3e1 * t31 * t34 * (0.26456532405541184982e-1 * sigma[2] / t124 / rho[1] * t44 - 0.41287072352122365489e-3 * t129 / t342 * t134 + 0.18040695917302508518e-5 * t129 * sigma[2] / t342 / t36 * t353));
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[2] = 0.2e1 * t112 + 0.2e1 * t142 + t6 * (t315 + t361);

  t368 = t5 * t58 * t152;
  t389 = my_piecewise3(t2, 0, -0.8e1 / 0.3e1 * t52 * t11 * t152 + 0.4e1 / 0.3e1 * t368 - 0.4e1 / 0.3e1 * t62 * t63 * t152 * t68 - 0.8e1 / 0.3e1 * t5 * t12 * (-0.66141331013852962455e-2 * t73 * t22 + 0.12386121705636709647e-3 * t79 * t82 * sigma[0] - 0.60135653057675028394e-6 * t77 / t213 / t13 * t224));
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[0] = t6 * t389 + t156;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[1] = 0.0e0;

  t392 = t31 * t91 * t164;
  t397 = my_piecewise3(t30, 0, 0.4e1 / 0.3e1 * t94 * t98 * t164 + 0.4e1 / 0.3e1 * t392);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[2] = t6 * t397 + t168;

  t403 = my_piecewise3(t2, 0, 0.4e1 / 0.3e1 * t106 * t107 * t152 + 0.4e1 / 0.3e1 * t368);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[3] = t6 * t403 + t156;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[4] = 0.0e0;

  t428 = my_piecewise3(t30, 0, -0.8e1 / 0.3e1 * t52 * t33 * t164 + 0.4e1 / 0.3e1 * t392 - 0.4e1 / 0.3e1 * t117 * t97 * t164 * t120 - 0.8e1 / 0.3e1 * t31 * t34 * (-0.66141331013852962455e-2 * t125 * t44 + 0.12386121705636709647e-3 * t131 * t134 * sigma[2] - 0.60135653057675028394e-6 * t129 / t342 / t35 * t353));
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[5] = t6 * t428 + t168;

  t441 = my_piecewise3(t2, 0, -0.8e1 / 0.3e1 * t5 * t12 * (-0.27524714901414910326e-4 * t148 * t82 + 0.20045217685891676131e-6 * sigma[0] / t213 / rho[0] * t224));
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[0] = t6 * t441;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[1] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[2] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[3] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[4] = 0.0e0;

  t453 = my_piecewise3(t30, 0, -0.8e1 / 0.3e1 * t31 * t34 * (-0.27524714901414910326e-4 * t160 * t134 + 0.20045217685891676131e-6 * sigma[2] / t342 / rho[1] * t353));
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[5] = t6 * t453;

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


#endif

#endif

#endif


}

