/* 
  This file was generated automatically with ./scripts/maple2c.pl.
  Do not edit this file directly as it can be overwritten!!

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Maple version     : Maple 2016 (X86 64 LINUX)
  Maple source      : ./maple/gga_exc/gga_c_w94.mpl
  Type of functional: gga_exc
*/

#define maple2c_order 2
#define MAPLE2C_FLAGS (XC_FLAGS_I_HAVE_EXC | XC_FLAGS_I_HAVE_VXC | XC_FLAGS_I_HAVE_FXC)


static inline void
func_unpol(const xc_func_type *p, int order, const double *rho, const double *sigma , double *zk GGA_OUT_PARAMS_NO_EXC(XC_COMMA double *, ))
{

#ifndef XC_DONT_COMPILE_EXC
  double t1, t2, t3, t4, t5, t7, t9, t10;
  double t11, t12, t13, t16, t17, t20, t22, t23;
  double t24, t25, t30;

#ifndef XC_DONT_COMPILE_VXC
  double t32, t33, t34, t35, t37, t39, t40, t42;
  double t50, t53, t57;

#ifndef XC_DONT_COMPILE_FXC
  double t62, t63, t66, t98;
#endif

#endif

#endif



  t1 = sqrt(sigma[0]);
  t2 = t1 * sigma[0];
  t3 = rho[0] * rho[0];
  t4 = t3 * t3;
  t5 = 0.1e1 / t4;
  t7 = POW_1_3(rho[0]);
  t9 = 0.1e1 / t7 / rho[0];
  t10 = t1 * t9;
  t11 = pow(t10, 0.1e1 / 0.16e2);
  t12 = t11 * t11;
  t13 = t12 * t11;
  t16 = t3 * rho[0];
  t17 = 0.1e1 / t16;
  t20 = M_CBRT3;
  t22 = POW_1_3(0.1e1 / M_PI);
  t23 = t20 * t22;
  t24 = M_CBRT4;
  t25 = t24 * t24;
  t30 = 0.118e2 + 0.150670e0 * t13 * t2 * t5 + 0.11020000000000000000e-1 * sigma[0] * t17 + t23 * t25 / t7 / 0.4e1;
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    zk[0] = -0.1e1 / t30;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  t32 = t30 * t30;
  t33 = 0.1e1 / t32;
  t34 = rho[0] * t33;
  t35 = t7 * t7;
  t37 = 0.1e1 / t35 / t3;
  t39 = t13 * sigma[0] * t37;
  t40 = t39 * t1;
  t42 = 0.1e1 / t7 / t3;
  t50 = -0.64034750000000000000e0 * t40 * t42 - 0.33060000000000000000e-1 * sigma[0] * t5 - t23 * t25 * t9 / 0.12e2;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = t34 * t50 + (-0.1e1 / t30);

  t53 = t39 / t1;
  t57 = 0.24013031250000000000e0 * t53 * t9 + 0.11020000000000000000e-1 * t17;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[0] = t34 * t57;

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t62 = rho[0] / t32 / t30;
  t63 = t50 * t50;
  t66 = t13 * t10;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = 0.2e1 * t33 * t50 - 0.2e1 * t62 * t63 + t34 * (0.18676802083333333333e1 * t66 * sigma[0] / t35 / t4 + 0.14941441666666666667e1 * t40 / t7 / t16 + 0.13224000000000000000e0 * sigma[0] / t4 / rho[0] + t23 * t25 * t42 / 0.9e1);

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[0] = t33 * t57 - 0.2e1 * t62 * t57 * t50 + t34 * (-0.70038007812500000000e0 * t66 / t35 / t16 - 0.32017375000000000000e0 * t53 * t42 - 0.33060000000000000000e-1 * t5);

  t98 = t57 * t57;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[0] = -0.2e1 * t62 * t98 + t34 * (0.26264252929687500000e0 * t66 / sigma[0] * t37 - 0.12006515625000000000e0 * t39 / t2 * t9);

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


#endif

#endif

#endif


}


static inline void
func_pol(const xc_func_type *p, int order, const double *rho, const double *sigma , double *zk GGA_OUT_PARAMS_NO_EXC(XC_COMMA double *, ))
{

#ifndef XC_DONT_COMPILE_EXC
  double t1, t2, t3, t4, t5, t6, t7, t8;
  double t9, t10, t12, t13, t15, t16, t17, t18;
  double t19, t20, t22, t24, t25, t26, t27, t28;
  double t31, t32, t35, t37, t38, t39, t40, t45;
  double t46;

#ifndef XC_DONT_COMPILE_VXC
  double t48, t49, t50, t51, t52, t53, t55, t56;
  double t60, t61, t62, t63, t65, t67, t68, t70;
  double t78, t80, t81, t83, t84, t89, t90, t93;
  double t97;

#ifndef XC_DONT_COMPILE_FXC
  double t99, t100, t101, t103, t105, t108, t109, t110;
  double t111, t115, t117, t119, t120, t124, t126, t128;
  double t129, t134, t135, t138, t139, t158, t160, t161;
  double t169, t176, t177, t178, t184, t193, t195, t196;
  double t200, t201, t208, t211, t213, t218, t219, t220;
  double t224, t227, t233, t240, t246, t250, t263;
#endif

#endif

#endif



  t1 = rho[0] - rho[1];
  t2 = rho[0] + rho[1];
  t3 = 0.1e1 / t2;
  t4 = t1 * t3;
  t5 = 0.0e0 < t4;
  t6 = my_piecewise3(t5, t4, -t4);
  t7 = 0.1e-9 < t6;
  t8 = my_piecewise3(t7, t6, 0.1e-9);
  t9 = POW_1_3(t8);
  t10 = t9 * t9;
  t12 = -t10 * t8 + 0.1e1;
  t13 = sqrt(t12);
  t15 = sigma[0] + 0.2e1 * sigma[1] + sigma[2];
  t16 = sqrt(t15);
  t17 = t16 * t15;
  t18 = t2 * t2;
  t19 = t18 * t18;
  t20 = 0.1e1 / t19;
  t22 = POW_1_3(t2);
  t24 = 0.1e1 / t22 / t2;
  t25 = t16 * t24;
  t26 = pow(t25, 0.1e1 / 0.16e2);
  t27 = t26 * t26;
  t28 = t27 * t26;
  t31 = t18 * t2;
  t32 = 0.1e1 / t31;
  t35 = M_CBRT3;
  t37 = POW_1_3(0.1e1 / M_PI);
  t38 = t35 * t37;
  t39 = M_CBRT4;
  t40 = t39 * t39;
  t45 = 0.118e2 + 0.150670e0 * t28 * t17 * t20 + 0.11020000000000000000e-1 * t15 * t32 + t38 * t40 / t22 / 0.4e1;
  t46 = 0.1e1 / t45;
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    zk[0] = -t13 * t46;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  t48 = 0.1e1 / t13;
  t49 = t2 * t48;
  t50 = t46 * t10;
  t51 = 0.1e1 / t18;
  t52 = t1 * t51;
  t53 = t3 - t52;
  t55 = my_piecewise3(t5, t53, -t53);
  t56 = my_piecewise3(t7, t55, 0);
  t60 = t2 * t13;
  t61 = t45 * t45;
  t62 = 0.1e1 / t61;
  t63 = t22 * t22;
  t65 = 0.1e1 / t63 / t18;
  t67 = t28 * t15 * t65;
  t68 = t67 * t16;
  t70 = 0.1e1 / t22 / t18;
  t78 = -0.64034750000000000000e0 * t68 * t70 - 0.33060000000000000000e-1 * t15 * t20 - t38 * t40 * t24 / 0.12e2;
  t80 = t60 * t62 * t78;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = (-t13 * t46) + 0.5e1 / 0.6e1 * t49 * t50 * t56 + t80;

  t81 = -t3 - t52;
  t83 = my_piecewise3(t5, t81, -t81);
  t84 = my_piecewise3(t7, t83, 0);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[1] = (-t13 * t46) + 0.5e1 / 0.6e1 * t49 * t50 * t84 + t80;

  t89 = t67 / t16;
  t90 = t89 * t24;
  t93 = 0.24013031250000000000e0 * t90 + 0.11020000000000000000e-1 * t32;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[0] = t60 * t62 * t93;

  t97 = 0.48026062500000000000e0 * t90 + 0.22040000000000000000e-1 * t32;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[1] = t60 * t62 * t97;

  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[2] = vsigma[0];

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t99 = t48 * t46;
  t100 = t10 * t56;
  t101 = t99 * t100;
  t103 = t13 * t62;
  t105 = 0.2e1 * t103 * t78;
  t108 = t2 / t13 / t12;
  t109 = t9 * t8;
  t110 = t46 * t109;
  t111 = t56 * t56;
  t115 = t49 * t62;
  t117 = t115 * t100 * t78;
  t119 = 0.1e1 / t9;
  t120 = t46 * t119;
  t124 = t1 * t32;
  t126 = -0.2e1 * t51 + 0.2e1 * t124;
  t128 = my_piecewise3(t5, t126, -t126);
  t129 = my_piecewise3(t7, t128, 0);
  t134 = 0.1e1 / t61 / t45;
  t135 = t78 * t78;
  t138 = 0.2e1 * t60 * t134 * t135;
  t139 = t28 * t25;
  t158 = t60 * t62 * (0.18676802083333333333e1 * t139 * t15 / t63 / t19 + 0.14941441666666666667e1 * t68 / t22 / t31 + 0.13224000000000000000e0 * t15 / t19 / t2 + t38 * t40 * t70 / 0.9e1);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = 0.5e1 / 0.3e1 * t101 + t105 + 0.25e2 / 0.36e2 * t108 * t110 * t111 - 0.5e1 / 0.3e1 * t117 + 0.5e1 / 0.9e1 * t49 * t120 * t111 + 0.5e1 / 0.6e1 * t49 * t50 * t129 - t138 + t158;

  t160 = t10 * t84;
  t161 = t99 * t160;
  t169 = t115 * t160 * t78;
  t176 = 0.2e1 * t124;
  t177 = my_piecewise3(t5, t176, -t176);
  t178 = my_piecewise3(t7, t177, 0);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[1] = 0.5e1 / 0.6e1 * t101 + t105 + 0.5e1 / 0.6e1 * t161 + 0.25e2 / 0.36e2 * t108 * t46 * t109 * t84 * t56 - 0.5e1 / 0.6e1 * t169 + 0.5e1 / 0.9e1 * t49 * t46 * t119 * t84 * t56 + 0.5e1 / 0.6e1 * t49 * t50 * t178 - 0.5e1 / 0.6e1 * t117 - t138 + t158;

  t184 = t84 * t84;
  t193 = 0.2e1 * t51 + 0.2e1 * t124;
  t195 = my_piecewise3(t5, t193, -t193);
  t196 = my_piecewise3(t7, t195, 0);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[2] = 0.5e1 / 0.3e1 * t161 + t105 + 0.25e2 / 0.36e2 * t108 * t110 * t184 - 0.5e1 / 0.3e1 * t169 + 0.5e1 / 0.9e1 * t49 * t120 * t184 + 0.5e1 / 0.6e1 * t49 * t50 * t196 - t138 + t158;

  t200 = t103 * t93;
  t201 = t93 * t10;
  t208 = 0.2e1 * t60 * t134 * t93 * t78;
  t211 = t139 / t63 / t31;
  t213 = t89 * t70;
  t218 = t60 * t62 * (-0.70038007812500000000e0 * t211 - 0.32017375000000000000e0 * t213 - 0.33060000000000000000e-1 * t20);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[0] = t200 - 0.5e1 / 0.6e1 * t115 * t201 * t56 - t208 + t218;

  t219 = t103 * t97;
  t220 = t97 * t10;
  t224 = t134 * t97;
  t227 = 0.2e1 * t60 * t224 * t78;
  t233 = t60 * t62 * (-0.14007601562500000000e1 * t211 - 0.64034750000000000000e0 * t213 - 0.66120000000000000000e-1 * t20);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[1] = t219 - 0.5e1 / 0.6e1 * t115 * t220 * t56 - t227 + t233;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[2] = v2rhosigma[0];

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[3] = t200 - 0.5e1 / 0.6e1 * t115 * t201 * t84 - t208 + t218;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[4] = t219 - 0.5e1 / 0.6e1 * t115 * t220 * t84 - t227 + t233;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[5] = v2rhosigma[3];

  t240 = t93 * t93;
  t246 = t139 / t15 * t65;
  t250 = t67 / t17 * t24;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[0] = -0.2e1 * t60 * t134 * t240 + t60 * t62 * (0.26264252929687500000e0 * t246 - 0.12006515625000000000e0 * t250);

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[1] = -0.2e1 * t60 * t224 * t93 + t60 * t62 * (0.52528505859375000000e0 * t246 - 0.24013031250000000000e0 * t250);

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[2] = v2sigma2[0];

  t263 = t97 * t97;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[3] = -0.2e1 * t60 * t134 * t263 + t60 * t62 * (0.10505701171875000000e1 * t246 - 0.48026062500000000000e0 * t250);

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[4] = v2sigma2[1];

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[5] = v2sigma2[2];

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


#endif

#endif

#endif


}

