/* 
  This file was generated automatically with ./scripts/maple2c.pl.
  Do not edit this file directly as it can be overwritten!!

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Maple version     : Maple 2016 (X86 64 LINUX)
  Maple source      : ./maple/gga_exc/gga_x_q2d.mpl
  Type of functional: gga_exc
*/

#define maple2c_order 2
#define MAPLE2C_FLAGS (XC_FLAGS_I_HAVE_EXC | XC_FLAGS_I_HAVE_VXC | XC_FLAGS_I_HAVE_FXC)


static inline void
func_unpol(const xc_func_type *p, int order, const double *rho, const double *sigma , double *zk GGA_OUT_PARAMS_NO_EXC(XC_COMMA double *, ))
{

#ifndef XC_DONT_COMPILE_EXC
  double t3, t4, t5, t7, t8, t9, t10, t11;
  double t12, t13, t15, t16, t17, t18, t19, t21;
  double t23, t25, t28, t29, t31, t33, t34, t35;
  double t36, t38, t42, t44, t46, t49, t51, t52;
  double t54, t57, t59, t60, t61, t63, t64, t67;
  double t68, t72;

#ifndef XC_DONT_COMPILE_VXC
  double t73, t78, t79, t81, t82, t84, t89, t90;
  double t91, t93, t97, t99, t100, t103, t107, t108;
  double t112, t119, t122, t123, t124, t125, t126, t130;
  double t133, t137, t141, t142, t143, t147, t151, t156;
  double t159, t160, t164;

#ifndef XC_DONT_COMPILE_FXC
  double t177, t186, t188, t194, t199, t201, t211, t213;
  double t220, t221, t240, t244, t247, t248, t255, t256;
  double t262, t278, t288, t305, t322, t372;
#endif

#endif

#endif



  t3 = rho[0] / 0.2e1 <= 0.101e1 * p->threshold_dens;
  t4 = M_CBRT3;
  t5 = M_CBRTPI;
  t7 = t4 / t5;
  t8 = POW_1_3(rho[0]);
  t9 = M_CBRT6;
  t10 = M_PI * M_PI;
  t11 = POW_1_3(t10);
  t12 = t11 * t11;
  t13 = 0.1e1 / t12;
  t15 = M_CBRT2;
  t16 = t15 * t15;
  t17 = sigma[0] * t16;
  t18 = rho[0] * rho[0];
  t19 = t8 * t8;
  t21 = 0.1e1 / t19 / t18;
  t23 = t9 * t13 * t17 * t21;
  t25 = 0.8040e0 + 0.5e1 / 0.972e3 * t23;
  t28 = 0.18040e1 - 0.64641600e0 / t25;
  t29 = t9 * t9;
  t31 = 0.1e1 / t11 / t10;
  t33 = sigma[0] * sigma[0];
  t34 = t33 * t15;
  t35 = t18 * t18;
  t36 = t35 * rho[0];
  t38 = 0.1e1 / t8 / t36;
  t42 = 0.100e3 - t29 * t31 * t34 * t38 / 0.288e3;
  t44 = 0.1e1 / t11;
  t46 = sqrt(sigma[0]);
  t49 = 0.1e1 / t8 / rho[0];
  t51 = t29 * t44 * t46 * t15 * t49;
  t52 = pow(t51, 0.35e1);
  t54 = 0.1e1 + t23 / 0.24e2;
  t57 = t28 * t42 + 0.87153829697982569831e-4 * t52 * t54;
  t59 = t10 * t10;
  t60 = 0.1e1 / t59;
  t61 = t33 * sigma[0];
  t63 = t35 * t35;
  t64 = 0.1e1 / t63;
  t67 = 0.100e3 + t60 * t61 * t64 / 0.576e3;
  t68 = 0.1e1 / t67;
  t72 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t7 * t8 * t57 * t68);
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    zk[0] = 0.2e1 * t72;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  t73 = 0.1e1 / t19;
  t78 = t25 * t25;
  t79 = 0.1e1 / t78;
  t81 = t79 * t9 * t13;
  t82 = t18 * rho[0];
  t84 = 0.1e1 / t19 / t82;
  t89 = t28 * t29;
  t90 = t89 * t31;
  t91 = t35 * t18;
  t93 = 0.1e1 / t8 / t91;
  t97 = pow(t51, 0.25e1);
  t99 = t97 * t54 * t29;
  t100 = t44 * t46;
  t103 = t15 / t8 / t18;
  t107 = t52 * t9;
  t108 = t107 * t13;
  t112 = -0.88671604938271604938e-2 * t81 * t17 * t84 * t42 + t90 * t34 * t93 / 0.54e2 - 0.40671787192391865921e-3 * t99 * t100 * t103 - 0.96837588553313966479e-5 * t108 * t17 * t84;
  t119 = t4 / t5 / t59;
  t122 = t119 / t19 / t63;
  t123 = t67 * t67;
  t124 = 0.1e1 / t123;
  t125 = t57 * t124;
  t126 = t125 * t61;
  t130 = my_piecewise3(t3, 0, -t7 * t73 * t57 * t68 / 0.8e1 - 0.3e1 / 0.8e1 * t7 * t8 * t112 * t68 - t122 * t126 / 0.192e3);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = 0.2e1 * rho[0] * t130 + 0.2e1 * t72;

  t133 = t16 * t21;
  t137 = sigma[0] * t15;
  t141 = 0.1e1 / t46;
  t142 = t44 * t141;
  t143 = t15 * t49;
  t147 = t13 * t16;
  t151 = 0.33251851851851851852e-2 * t81 * t133 * t42 - t90 * t137 * t38 / 0.144e3 + 0.15251920197146949720e-3 * t99 * t142 * t143 + 0.36314095707492737430e-5 * t107 * t147 * t21;
  t156 = t35 * t82;
  t159 = t119 / t19 / t156;
  t160 = t125 * t33;
  t164 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t7 * t8 * t151 * t68 + t159 * t160 / 0.512e3);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[0] = 0.2e1 * rho[0] * t164;

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t177 = t63 * rho[0];
  t186 = 0.1e1 / t78 / t25 * t29 * t31;
  t188 = 0.1e1 / t8 / t156;
  t194 = 0.1e1 / t19 / t35;
  t199 = t79 * t60;
  t201 = 0.1e1 / t63 / t18;
  t211 = POW_3_2(t51);
  t213 = t211 * t54 * t9;
  t220 = t97 / t10;
  t221 = t46 * sigma[0];
  t240 = t112 * t124;
  t244 = t59 * t59;
  t247 = t4 / t5 / t244;
  t248 = t63 * t63;
  t255 = t57 / t123 / t67;
  t256 = t33 * t33;
  t262 = my_piecewise3(t3, 0, t7 / t19 / rho[0] * t57 * t68 / 0.12e2 - t7 * t73 * t112 * t68 / 0.4e1 + 0.25e2 / 0.576e3 * t119 / t19 / t177 * t126 - 0.3e1 / 0.8e1 * t7 * t8 * (-0.48653829870107876509e-3 * t186 * t34 * t188 * t42 + 0.32512921810699588477e-1 * t81 * t17 * t194 * t42 - 0.19704801097393689986e-2 * t199 * t61 * t201 - 0.20228913839792803583e-4 * t79 * t61 * t201 - 0.19e2 / 0.162e3 * t90 * t34 * t188 + 0.81343574384783731842e-2 * t213 * t13 * sigma[0] * t16 * t194 + 0.10845809917971164246e-2 * t220 * t221 / t91 + 0.94900836782247687149e-3 * t99 * t100 * t15 / t8 / t82 + 0.35507115802881787709e-4 * t108 * t17 * t194) * t68 - t122 * t240 * t61 / 0.96e2 - t247 / t19 / t248 / rho[0] * t255 * t256 * t33 / 0.6912e4);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = 0.2e1 * rho[0] * t262 + 0.4e1 * t130;

  t278 = 0.1e1 / t177;
  t288 = t147 * t84;
  t305 = t151 * t124;
  t322 = my_piecewise3(t3, 0, -t7 * t73 * t151 * t68 / 0.8e1 - 0.3e1 / 0.8e1 * t7 * t8 * (0.18245186201290453691e-3 * t186 * t15 * t93 * t42 * sigma[0] - 0.88671604938271604939e-2 * t81 * t16 * t84 * t42 + 0.73893004115226337449e-3 * t199 * t278 * t33 + 0.75858426899223013437e-5 * t79 * t33 * t278 + t90 * t137 * t93 / 0.27e2 - 0.30503840394293899440e-2 * t213 * t288 - 0.40671787192391865921e-3 * t220 * t46 / t36 - 0.20335893596195932960e-3 * t99 * t142 * t103 - 0.96837588553313966480e-5 * t107 * t288) * t68 - t122 * t305 * t61 / 0.192e3 - 0.23e2 / 0.1536e4 * t122 * t160 + t159 * t240 * t33 / 0.512e3 + t247 / t19 / t248 * t255 * t256 * sigma[0] / 0.18432e5);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[0] = 0.2e1 * rho[0] * t322 + 0.2e1 * t164;

  t372 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t7 * t8 * (-0.68419448254839201342e-4 * t186 * t15 * t38 * t42 - 0.27709876543209876543e-3 * t199 * t64 * sigma[0] - 0.28446910087208630037e-5 * t79 * t64 * sigma[0] - t89 * t31 * t15 * t38 / 0.144e3 + 0.11438940147860212290e-2 * t213 * t13 / sigma[0] * t133 + 0.15251920197146949720e-3 * t220 / t35 * t141 - 0.76259600985734748600e-4 * t99 * t44 / t221 * t143) * t68 + t159 * t305 * t33 / 0.256e3 - t247 / t19 / t63 / t156 * t255 * t256 / 0.49152e5 + t159 * t125 * sigma[0] / 0.256e3);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[0] = 0.2e1 * rho[0] * t372;

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


#endif

#endif

#endif


}


static inline void
func_pol(const xc_func_type *p, int order, const double *rho, const double *sigma , double *zk GGA_OUT_PARAMS_NO_EXC(XC_COMMA double *, ))
{

#ifndef XC_DONT_COMPILE_EXC
  double t1, t2, t3, t4, t6, t7, t9, t10;
  double t11, t12, t13, t14, t15, t16, t17, t18;
  double t19, t20, t21, t22, t23, t24, t25, t26;
  double t28, t30, t32, t35, t36, t38, t39, t40;
  double t41, t42, t44, t48, t50, t51, t52, t54;
  double t56, t57, t59, t62, t63, t64, t65, t67;
  double t68, t71, t72, t73, t74, t77, t78, t80;
  double t81, t82, t83, t84, t85, t86, t88, t90;
  double t92, t95, t96, t97, t98, t100, t104, t106;
  double t108, t110, t111, t113, t116, t117, t119, t120;
  double t123, t124, t125, t126, t129;

#ifndef XC_DONT_COMPILE_VXC
  double t130, t134, t135, t136, t138, t139, t140, t141;
  double t142, t143, t145, t146, t150, t151, t152, t153;
  double t154, t156, t161, t162, t163, t165, t169, t171;
  double t172, t174, t178, t179, t183, t184, t185, t190;
  double t191, t192, t193, t194, t195, t196, t201, t202;
  double t203, t205, t207, t209, t210, t211, t212, t217;
  double t221, t222, t223, t227, t230, t232, t233, t237;
  double t238, t239, t240, t241, t243, t248, t249, t250;
  double t252, t256, t258, t259, t261, t265, t266, t270;
  double t271, t272, t275, t276, t277, t278, t279, t280;
  double t285, t288, t292, t296, t297, t303, t304, t305;
  double t308, t310, t311, t312, t313, t317, t318, t322;
  double t326, t327, t333, t334, t335, t338, t340, t341;
  double t342, t343, t347;

#ifndef XC_DONT_COMPILE_FXC
  double t350, t351, t352, t353, t359, t362, t363, t365;
  double t371, t376, t378, t388, t389, t390, t391, t394;
  double t395, t396, t397, t413, t417, t425, t428, t431;
  double t437, t438, t446, t451, t454, t455, t462, t463;
  double t472, t474, t486, t487, t491, t493, t496, t500;
  double t502, t504, t510, t521, t534, t535, t539, t547;
  double t553, t561, t567, t572, t573, t586, t593, t594;
  double t596, t602, t607, t609, t619, t620, t621, t622;
  double t625, t626, t627, t646, t661, t666, t673, t674;
  double t685, t697, t698, t705, t714, t744, t753, t774;
  double t778, t784, t791, t802, t814, t844, t871, t873;
  double t921, t922, t970;
#endif

#endif

#endif



  t1 = 0.101e1 * p->threshold_dens;
  t2 = rho[0] <= t1;
  t3 = M_CBRT3;
  t4 = M_CBRTPI;
  t6 = t3 / t4;
  t7 = M_CBRT2;
  t9 = t6 * t7 * rho[0];
  t10 = rho[0] + rho[1];
  t11 = POW_1_3(t10);
  t12 = t11 * t11;
  t13 = 0.1e1 / t12;
  t14 = 0.1e1 / t10;
  t15 = rho[0] * t14;
  t16 = POW_1_3(t15);
  t17 = t13 * t16;
  t18 = M_CBRT6;
  t19 = M_PI * M_PI;
  t20 = POW_1_3(t19);
  t21 = t20 * t20;
  t22 = 0.1e1 / t21;
  t23 = t18 * t22;
  t24 = rho[0] * rho[0];
  t25 = POW_1_3(rho[0]);
  t26 = t25 * t25;
  t28 = 0.1e1 / t26 / t24;
  t30 = t23 * sigma[0] * t28;
  t32 = 0.8040e0 + 0.5e1 / 0.972e3 * t30;
  t35 = 0.18040e1 - 0.64641600e0 / t32;
  t36 = t18 * t18;
  t38 = 0.1e1 / t20 / t19;
  t39 = t36 * t38;
  t40 = sigma[0] * sigma[0];
  t41 = t24 * t24;
  t42 = t41 * rho[0];
  t44 = 0.1e1 / t25 / t42;
  t48 = 0.100e3 - t39 * t40 * t44 / 0.576e3;
  t50 = 0.1e1 / t20;
  t51 = t36 * t50;
  t52 = sqrt(sigma[0]);
  t54 = 0.1e1 / t25 / rho[0];
  t56 = t51 * t52 * t54;
  t57 = pow(t56, 0.35e1);
  t59 = 0.1e1 + t30 / 0.24e2;
  t62 = t35 * t48 + 0.87153829697982569831e-4 * t57 * t59;
  t63 = t19 * t19;
  t64 = 0.1e1 / t63;
  t65 = t40 * sigma[0];
  t67 = t41 * t41;
  t68 = 0.1e1 / t67;
  t71 = 0.100e3 + t64 * t65 * t68 / 0.2304e4;
  t72 = 0.1e1 / t71;
  t73 = t62 * t72;
  t74 = t17 * t73;
  t77 = my_piecewise3(t2, 0, -0.3e1 / 0.4e1 * t9 * t74);
  t78 = rho[1] <= t1;
  t80 = t6 * t7 * rho[1];
  t81 = rho[1] * t14;
  t82 = POW_1_3(t81);
  t83 = t13 * t82;
  t84 = rho[1] * rho[1];
  t85 = POW_1_3(rho[1]);
  t86 = t85 * t85;
  t88 = 0.1e1 / t86 / t84;
  t90 = t23 * sigma[2] * t88;
  t92 = 0.8040e0 + 0.5e1 / 0.972e3 * t90;
  t95 = 0.18040e1 - 0.64641600e0 / t92;
  t96 = sigma[2] * sigma[2];
  t97 = t84 * t84;
  t98 = t97 * rho[1];
  t100 = 0.1e1 / t85 / t98;
  t104 = 0.100e3 - t39 * t96 * t100 / 0.576e3;
  t106 = sqrt(sigma[2]);
  t108 = 0.1e1 / t85 / rho[1];
  t110 = t51 * t106 * t108;
  t111 = pow(t110, 0.35e1);
  t113 = 0.1e1 + t90 / 0.24e2;
  t116 = t95 * t104 + 0.87153829697982569831e-4 * t111 * t113;
  t117 = t96 * sigma[2];
  t119 = t97 * t97;
  t120 = 0.1e1 / t119;
  t123 = 0.100e3 + t64 * t117 * t120 / 0.2304e4;
  t124 = 0.1e1 / t123;
  t125 = t116 * t124;
  t126 = t83 * t125;
  t129 = my_piecewise3(t78, 0, -0.3e1 / 0.4e1 * t80 * t126);
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    zk[0] = t77 + t129;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  t130 = t6 * t7;
  t134 = 0.1e1 / t12 / t10;
  t135 = t134 * t16;
  t136 = t135 * t73;
  t138 = t9 * t136 / 0.2e1;
  t139 = t16 * t16;
  t140 = 0.1e1 / t139;
  t141 = t13 * t140;
  t142 = t10 * t10;
  t143 = 0.1e1 / t142;
  t145 = -rho[0] * t143 + t14;
  t146 = t73 * t145;
  t150 = t32 * t32;
  t151 = 0.1e1 / t150;
  t152 = t151 * t18;
  t153 = t152 * t22;
  t154 = t24 * rho[0];
  t156 = 0.1e1 / t26 / t154;
  t161 = t35 * t36;
  t162 = t38 * t40;
  t163 = t41 * t24;
  t165 = 0.1e1 / t25 / t163;
  t169 = pow(t56, 0.25e1);
  t171 = t169 * t59 * t36;
  t172 = t50 * t52;
  t174 = 0.1e1 / t25 / t24;
  t178 = t57 * t18;
  t179 = t22 * sigma[0];
  t183 = -0.88671604938271604938e-2 * t153 * sigma[0] * t156 * t48 + t161 * t162 * t165 / 0.108e3 - 0.40671787192391865921e-3 * t171 * t172 * t174 - 0.96837588553313966479e-5 * t178 * t179 * t156;
  t184 = t183 * t72;
  t185 = t17 * t184;
  t190 = t3 / t4 / t63;
  t191 = t7 * t68;
  t192 = t190 * t191;
  t193 = t71 * t71;
  t194 = 0.1e1 / t193;
  t195 = t62 * t194;
  t196 = t195 * t65;
  t201 = my_piecewise3(t2, 0, -0.3e1 / 0.4e1 * t130 * t74 + t138 - t9 * t141 * t146 / 0.4e1 - 0.3e1 / 0.4e1 * t9 * t185 - t192 * t17 * t196 / 0.384e3);
  t202 = t134 * t82;
  t203 = t202 * t125;
  t205 = t80 * t203 / 0.2e1;
  t207 = t6 * t7 * t84;
  t209 = 0.1e1 / t12 / t142;
  t210 = t82 * t82;
  t211 = 0.1e1 / t210;
  t212 = t209 * t211;
  t217 = my_piecewise3(t78, 0, t205 + t207 * t212 * t125 / 0.4e1);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = t77 + t129 + t10 * (t201 + t217);

  t221 = t6 * t7 * t24;
  t222 = t209 * t140;
  t223 = t222 * t73;
  t227 = my_piecewise3(t2, 0, t138 + t221 * t223 / 0.4e1);
  t230 = t13 * t211;
  t232 = -rho[1] * t143 + t14;
  t233 = t125 * t232;
  t237 = t92 * t92;
  t238 = 0.1e1 / t237;
  t239 = t238 * t18;
  t240 = t239 * t22;
  t241 = t84 * rho[1];
  t243 = 0.1e1 / t86 / t241;
  t248 = t95 * t36;
  t249 = t38 * t96;
  t250 = t97 * t84;
  t252 = 0.1e1 / t85 / t250;
  t256 = pow(t110, 0.25e1);
  t258 = t256 * t113 * t36;
  t259 = t50 * t106;
  t261 = 0.1e1 / t85 / t84;
  t265 = t111 * t18;
  t266 = t22 * sigma[2];
  t270 = -0.88671604938271604938e-2 * t240 * sigma[2] * t243 * t104 + t248 * t249 * t252 / 0.108e3 - 0.40671787192391865921e-3 * t258 * t259 * t261 - 0.96837588553313966479e-5 * t265 * t266 * t243;
  t271 = t270 * t124;
  t272 = t83 * t271;
  t275 = t7 * t120;
  t276 = t190 * t275;
  t277 = t123 * t123;
  t278 = 0.1e1 / t277;
  t279 = t116 * t278;
  t280 = t279 * t117;
  t285 = my_piecewise3(t78, 0, -0.3e1 / 0.4e1 * t130 * t126 + t205 - t80 * t230 * t233 / 0.4e1 - 0.3e1 / 0.4e1 * t80 * t272 - t276 * t83 * t280 / 0.384e3);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[1] = t77 + t129 + t10 * (t227 + t285);

  t288 = t22 * t28;
  t292 = t38 * sigma[0];
  t296 = 0.1e1 / t52;
  t297 = t50 * t296;
  t303 = 0.33251851851851851852e-2 * t152 * t288 * t48 - t161 * t292 * t44 / 0.288e3 + 0.15251920197146949720e-3 * t171 * t297 * t54 + 0.36314095707492737430e-5 * t178 * t288;
  t304 = t303 * t72;
  t305 = t17 * t304;
  t308 = t41 * t154;
  t310 = t7 / t308;
  t311 = t190 * t310;
  t312 = t195 * t40;
  t313 = t17 * t312;
  t317 = my_piecewise3(t2, 0, -0.3e1 / 0.4e1 * t9 * t305 + t311 * t313 / 0.1024e4);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[0] = t10 * t317;

  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[1] = 0.0e0;

  t318 = t22 * t88;
  t322 = t38 * sigma[2];
  t326 = 0.1e1 / t106;
  t327 = t50 * t326;
  t333 = 0.33251851851851851852e-2 * t239 * t318 * t104 - t248 * t322 * t100 / 0.288e3 + 0.15251920197146949720e-3 * t258 * t327 * t108 + 0.36314095707492737430e-5 * t265 * t318;
  t334 = t333 * t124;
  t335 = t83 * t334;
  t338 = t97 * t241;
  t340 = t7 / t338;
  t341 = t190 * t340;
  t342 = t279 * t96;
  t343 = t83 * t342;
  t347 = my_piecewise3(t78, 0, -0.3e1 / 0.4e1 * t80 * t335 + t341 * t343 / 0.1024e4);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vsigma[2] = t10 * t347;

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t350 = t130 * t136;
  t351 = t7 * t13;
  t352 = t6 * t351;
  t353 = t140 * t62;
  t359 = t9 * t135 * t184;
  t362 = 0.1e1 / t150 / t32 * t36;
  t363 = t362 * t38;
  t365 = 0.1e1 / t25 / t308;
  t371 = 0.1e1 / t26 / t41;
  t376 = t151 * t64;
  t378 = 0.1e1 / t67 / t24;
  t388 = POW_3_2(t56);
  t389 = t388 * t59;
  t390 = t389 * t18;
  t391 = t179 * t371;
  t394 = 0.1e1 / t19;
  t395 = t169 * t394;
  t396 = t52 * sigma[0];
  t397 = 0.1e1 / t163;
  t413 = t190 * t351;
  t417 = 0.1e1 / t67 / rho[0];
  t425 = 0.5e1 / 0.6e1 * t9 * t209 * t16 * t73;
  t428 = t9 * t134 * t140 * t146;
  t431 = t192 * t135 * t196;
  t437 = t142 * t10;
  t438 = 0.1e1 / t437;
  t446 = t183 * t194;
  t451 = t63 * t63;
  t454 = t3 / t4 / t451;
  t455 = t67 * t67;
  t462 = t62 / t193 / t71;
  t463 = t40 * t40;
  t472 = 0.1e1 / t139 / t15;
  t474 = t145 * t145;
  t486 = t350 - t352 * t353 * t72 * t145 / 0.2e1 + t359 - 0.3e1 / 0.4e1 * t9 * t17 * (-0.24326914935053938255e-3 * t363 * t40 * t365 * t48 + 0.32512921810699588477e-1 * t153 * sigma[0] * t371 * t48 - 0.49262002743484224966e-3 * t376 * t65 * t378 - 0.50572284599482008956e-5 * t151 * t65 * t378 - 0.19e2 / 0.324e3 * t161 * t162 * t365 + 0.81343574384783731842e-2 * t390 * t391 + 0.54229049589855821228e-3 * t395 * t396 * t397 + 0.94900836782247687149e-3 * t171 * t172 / t25 / t154 + 0.35507115802881787709e-4 * t178 * t391) * t72 + 0.7e1 / 0.384e3 * t413 * t16 * t62 * t194 * t65 * t417 - t425 + t428 / 0.3e1 + t431 / 0.288e3 - t9 * t141 * t184 * t145 / 0.2e1 - t9 * t141 * t73 * (0.2e1 * rho[0] * t438 - 0.2e1 * t143) / 0.4e1 - t192 * t17 * t446 * t65 / 0.192e3 - t454 * t7 / t455 / rho[0] * t17 * t462 * t463 * t40 / 0.55296e5 - 0.3e1 / 0.2e1 * t130 * t185 + t9 * t13 * t472 * t73 * t474 / 0.6e1 - t190 * t191 * t13 * t353 * t194 * t145 * t65 / 0.576e3;
  t487 = my_piecewise3(t2, 0, t486);
  t491 = 0.5e1 / 0.6e1 * t80 * t209 * t82 * t125;
  t493 = 0.1e1 / t12 / t437;
  t496 = t207 * t493 * t211 * t125;
  t500 = t142 * t142;
  t502 = 0.1e1 / t12 / t500;
  t504 = 0.1e1 / t210 / t81;
  t510 = my_piecewise3(t78, 0, -t491 - 0.5e1 / 0.6e1 * t496 + t6 * t7 * t241 * t502 * t504 * t125 / 0.6e1);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = 0.2e1 * t201 + 0.2e1 * t217 + t10 * (t487 + t510);

  t521 = t221 * t493 * t140 * t73;
  t534 = my_piecewise3(t2, 0, t350 / 0.2e1 - t425 + t428 / 0.6e1 + t359 / 0.2e1 + t431 / 0.576e3 + t9 * t223 / 0.2e1 - 0.2e1 / 0.3e1 * t521 - t221 * t209 * t472 * t146 / 0.6e1 + t221 * t222 * t184 / 0.4e1 + t311 * t222 * t196 / 0.1152e4);
  t535 = t130 * t203;
  t539 = t211 * t116;
  t547 = t80 * t134 * t211 * t233;
  t553 = rho[1] * t438;
  t561 = t80 * t202 * t271;
  t567 = t276 * t202 * t280;
  t572 = t535 / 0.2e1 + t6 * t7 * t209 * t539 * t124 * rho[1] / 0.4e1 - t491 - t496 / 0.6e1 + t547 / 0.6e1 - t207 * t209 * t504 * t233 / 0.6e1 - t80 * t230 * t125 * (-t143 + 0.2e1 * t553) / 0.4e1 + t561 / 0.2e1 + t207 * t212 * t271 / 0.4e1 + t567 / 0.576e3 + t341 * t212 * t280 / 0.1152e4;
  t573 = my_piecewise3(t78, 0, t572);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[1] = t201 + t217 + t227 + t285 + t10 * (t534 + t573);

  t586 = my_piecewise3(t2, 0, -t425 - 0.5e1 / 0.6e1 * t521 + t6 * t7 * t154 * t502 * t472 * t73 / 0.6e1);
  t593 = 0.1e1 / t237 / t92 * t36;
  t594 = t593 * t38;
  t596 = 0.1e1 / t85 / t338;
  t602 = 0.1e1 / t86 / t97;
  t607 = t238 * t64;
  t609 = 0.1e1 / t119 / t84;
  t619 = POW_3_2(t110);
  t620 = t619 * t113;
  t621 = t620 * t18;
  t622 = t266 * t602;
  t625 = t256 * t394;
  t626 = t106 * sigma[2];
  t627 = 0.1e1 / t250;
  t646 = 0.1e1 / t119 / rho[1];
  t661 = t270 * t278;
  t666 = t119 * t119;
  t673 = t116 / t277 / t123;
  t674 = t96 * t96;
  t685 = t232 * t232;
  t697 = t535 - t352 * t539 * t124 * t232 / 0.2e1 - 0.3e1 / 0.4e1 * t80 * t83 * (-0.24326914935053938255e-3 * t594 * t96 * t596 * t104 + 0.32512921810699588477e-1 * t240 * sigma[2] * t602 * t104 - 0.49262002743484224966e-3 * t607 * t117 * t609 - 0.50572284599482008956e-5 * t238 * t117 * t609 - 0.19e2 / 0.324e3 * t248 * t249 * t596 + 0.81343574384783731842e-2 * t621 * t622 + 0.54229049589855821228e-3 * t625 * t626 * t627 + 0.94900836782247687149e-3 * t258 * t259 / t85 / t241 + 0.35507115802881787709e-4 * t265 * t622) * t124 - t491 + t561 + 0.7e1 / 0.384e3 * t413 * t82 * t116 * t278 * t117 * t646 - t80 * t230 * t271 * t232 / 0.2e1 - t80 * t230 * t125 * (-0.2e1 * t143 + 0.2e1 * t553) / 0.4e1 - t276 * t83 * t661 * t117 / 0.192e3 - t454 * t7 / t666 / rho[1] * t83 * t673 * t674 * t96 / 0.55296e5 - 0.3e1 / 0.2e1 * t130 * t272 + t547 / 0.3e1 + t567 / 0.288e3 + t80 * t13 * t504 * t125 * t685 / 0.6e1 - t190 * t275 * t13 * t539 * t278 * t232 * t117 / 0.576e3;
  t698 = my_piecewise3(t78, 0, t697);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[2] = 0.2e1 * t227 + 0.2e1 * t285 + t10 * (t586 + t698);

  t705 = t9 * t135 * t304 / 0.2e1;
  t714 = t22 * t156;
  t744 = t303 * t194;
  t753 = t311 * t135 * t312 / 0.1536e4;
  t774 = my_piecewise3(t2, 0, -0.3e1 / 0.4e1 * t130 * t305 + t705 - t9 * t141 * t304 * t145 / 0.4e1 - 0.3e1 / 0.4e1 * t9 * t17 * (0.91225931006452268455e-4 * t363 * t165 * t48 * sigma[0] - 0.88671604938271604939e-2 * t152 * t714 * t48 + 0.18473251028806584362e-3 * t376 * t417 * t40 + 0.18964606724805753359e-5 * t151 * t40 * t417 + t161 * t292 * t165 / 0.54e2 - 0.30503840394293899440e-2 * t389 * t23 * t156 - 0.20335893596195932960e-3 * t395 * t52 / t42 - 0.20335893596195932960e-3 * t171 * t297 * t174 - 0.96837588553313966480e-5 * t178 * t714) * t72 - t192 * t17 * t744 * t65 / 0.384e3 - 0.7e1 / 0.1024e4 * t192 * t313 - t753 + t190 * t310 * t13 * t353 * t194 * t40 * t145 / 0.3072e4 + t311 * t17 * t446 * t40 / 0.1024e4 + t454 * t7 / t455 * t17 * t462 * t463 * sigma[0] / 0.147456e6);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[0] = t10 * t774 + t317;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[1] = 0.0e0;

  t778 = t80 * t202 * t334 / 0.2e1;
  t784 = t341 * t202 * t342 / 0.1536e4;
  t791 = my_piecewise3(t78, 0, t778 + t207 * t212 * t334 / 0.4e1 - t784 - t190 * t7 * t627 * t212 * t342 / 0.3072e4);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[2] = t10 * t791 + t347;

  t802 = my_piecewise3(t2, 0, t705 + t221 * t222 * t304 / 0.4e1 - t753 - t190 * t7 * t397 * t222 * t312 / 0.3072e4);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[3] = t10 * t802 + t317;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[4] = 0.0e0;

  t814 = t22 * t243;
  t844 = t333 * t278;
  t871 = my_piecewise3(t78, 0, -0.3e1 / 0.4e1 * t130 * t335 + t778 - t80 * t230 * t334 * t232 / 0.4e1 - 0.3e1 / 0.4e1 * t80 * t83 * (0.91225931006452268455e-4 * t594 * t252 * t104 * sigma[2] - 0.88671604938271604939e-2 * t239 * t814 * t104 + 0.18473251028806584362e-3 * t607 * t646 * t96 + 0.18964606724805753359e-5 * t238 * t96 * t646 + t248 * t322 * t252 / 0.54e2 - 0.30503840394293899440e-2 * t620 * t23 * t243 - 0.20335893596195932960e-3 * t625 * t106 / t98 - 0.20335893596195932960e-3 * t258 * t327 * t261 - 0.96837588553313966480e-5 * t265 * t814) * t124 - t276 * t83 * t844 * t117 / 0.384e3 - 0.7e1 / 0.1024e4 * t276 * t343 - t784 + t190 * t340 * t13 * t539 * t278 * t96 * t232 / 0.3072e4 + t341 * t83 * t661 * t96 / 0.1024e4 + t454 * t7 / t666 * t83 * t673 * t674 * sigma[2] / 0.147456e6);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rhosigma[5] = t10 * t871 + t347;

  t873 = t38 * t44;
  t921 = my_piecewise3(t2, 0, -0.3e1 / 0.4e1 * t9 * t17 * (-0.34209724127419600671e-4 * t362 * t873 * t48 - 0.69274691358024691358e-4 * t376 * t68 * sigma[0] - 0.71117275218021575094e-6 * t151 * t68 * sigma[0] - t161 * t873 / 0.288e3 + 0.11438940147860212290e-2 * t390 * t22 / sigma[0] * t28 + 0.76259600985734748602e-4 * t395 / t41 * t296 - 0.76259600985734748600e-4 * t171 * t50 / t396 * t54) * t72 + t311 * t17 * t744 * t40 / 0.512e3 - t454 * t7 / t67 / t308 * t17 * t462 * t463 / 0.393216e6 + t311 * t17 * t195 * sigma[0] / 0.512e3);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[0] = t10 * t921;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[1] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[2] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[3] = 0.0e0;

  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[4] = 0.0e0;

  t922 = t38 * t100;
  t970 = my_piecewise3(t78, 0, -0.3e1 / 0.4e1 * t80 * t83 * (-0.34209724127419600671e-4 * t593 * t922 * t104 - 0.69274691358024691358e-4 * t607 * t120 * sigma[2] - 0.71117275218021575094e-6 * t238 * t120 * sigma[2] - t248 * t922 / 0.288e3 + 0.11438940147860212290e-2 * t621 * t22 / sigma[2] * t88 + 0.76259600985734748602e-4 * t625 / t97 * t326 - 0.76259600985734748600e-4 * t258 * t50 / t626 * t108) * t124 + t341 * t83 * t844 * t96 / 0.512e3 - t454 * t7 / t119 / t338 * t83 * t673 * t674 / 0.393216e6 + t341 * t83 * t279 * sigma[2] / 0.512e3);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2sigma2[5] = t10 * t970;

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


#endif

#endif

#endif


}

